### ISSUE TITLE
Add a LICENSE.md to the docs repo

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#1]
What we've historically used (e.g., for governance) is [Attribution-ShareAlike 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/) (CC BY-SA 4.0), but I don't think we want to force virality. Our code is Apache 2 and our docs should be Apache 2 like. For that reason, I think the license should be [Attribution 4.0 International](https://creativecommons.org/licenses/by/4.0/) (CC BY 4.0)

**Comment by adammichaelwood** [comment]
I agree with CC BY 4.0

**Comment by adammichaelwood** [comment]
Done
