### ISSUE TITLE
Explain adb

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#100]
- What it is
 - why use it
 - Where to get it
 - Install hangups not covered by adb's docs
 - where Collect app and data live in Android file system

**Comment by mish24** [comment]
Can you state some reliable resource I can refer to for making the doc?

**Comment by adammichaelwood** [comment]
https://developer.android.com/studio/command-line/adb.html

**Comment by adammichaelwood** [comment]
Things worth noting in doc:

 - adb comes with android studio, but it has to be enabled. There's also some bash config stuff to make the command work at terminal 
 - if you don't want to install android studio, adb is available as a standalone tool (https://developer.android.com/studio/releases/platform-tools.html)

**Comment by Divya063** [comment]
@adammichaelwood using adb with the custom Android emulator would take lot of time as the android emulator is very slow, why not use [genymotion](https://www.learn2crack.com/2013/08/setup-genymotion-windows.html) which is very fast as compared to custom android emulator

**Comment by adammichaelwood** [comment]
The "canonical" use of `adb` is with an actual device, attached via USB.

We provide some details on using Android Studio's emulator, but I don't think we want to suggest or officially support using other emulators -- especially since genymotion is a commercial, proprietary product.

**Comment by troublemagnet** [comment]
@adammichaelwood  I think 4 out of the 5 points stated in the issue description have already been addressed well. However can you please explain the 4th point?

**Comment by adammichaelwood** [comment]
However can you please explain the 4th point?

> Install hangups not covered by adb's docs

This is just general advice for writing about 3rd party tools. What *isn't* covered in their docs that would make it easier for *our* users.

But I do think this issue was completed by #140 and should have been closed.

**Comment by adammichaelwood** [comment]
Closed via #140
