### ISSUE TITLE
Central install problem on Digital Ocean fails on mail build

### ISSUE THREAD

**Issue by ivangayton** [opendatakit/docs#1005]
Trying to do an install of ODK Central on Digital Ocean. Followed the [documentation](https://docs.opendatakit.org/central-install-digital-ocean/) closely, though using ssh rather than a web console to talk to the server. 

It fails on the upgrade, seemingly long before any real work happens. It looks like a 404 on the Debian package server is the culprit: ```ERROR: Service 'mail' failed to build: The command '/bin/sh -c apt-get update && apt-get dist-upgrade -y' returned a non-zero code: 100``` (more of the console output below).

No huge urgency, and I haven't investigated further, but for people wanting to test Central I suspect this will be a snag. If someone has a really quick idea how to fix it that would be nice, and I'd be happy to give Central a try but don't have the time to debug the install process right now!

Onward,
Ivan

```root@xxxxx:~/central# docker-compose build
postgres uses an image, skipping
Building mail
Step 1/2 : FROM namshi/smtp
latest: Pulling from namshi/smtp
ff4229790957: Pull complete
bb7eb4b06654: Pull complete
cf932c8b3d1a: Pull complete
8adeef74c927: Pull complete
52aa0a29c308: Pull complete
Digest: sha256:e2ffb83e55fd71b2981ce16e0856441a679b31f56fa9dd95fa179fa473eb5f28
Status: Downloaded newer image for namshi/smtp:latest
 ---> f2dffd734243
Step 2/2 : RUN apt-get update && apt-get dist-upgrade -y
 ---> Running in e2727e9b158c
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:4 http://deb.debian.org jessie Release [148 kB]
Ign http://deb.debian.org jessie-updates Release
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  
Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
Fetched 10.1 MB in 7s (1389 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'mail' failed to build: The command '/bin/sh -c apt-get update && apt-get dist-upgrade -y' returned a non-zero code: 100
```

**Comment by yanokwa** [comment]
Thanks for reporting this, @ivangayton! It's an upstream problem and there is a duplicate issue at https://github.com/opendatakit/central/issues/64 so I'm closing this one.

**Comment by ivangayton** [comment]
Aha, didn't find that when glancing around for duplicate issues. Thanks Yaw!
