### ISSUE TITLE
rename PDF of ODK-X documentation to remove "ODK2" from filename

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/docs#1027]
user iamnarendrasingh on the forum posted:
> Today I was downloading ODK-X document from [Here](https://docs.opendatakit.org/odk-x/) and found that when I am downloading file , file name is "ODK2-Documentation", I think it should be ODK-X-Documentation.

https://forum.opendatakit.org/t/rename-of-downloading-file-of-odkx/19652

**Comment by roshanchittoor** [comment]
@danbjoseph I just validated this behavior. He is right. How can we fix this?
