### ISSUE TITLE
Switch Prev/Next buttons and file issue placement

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#103]
Would be better if page nav buttons were above the file an issue.

![screen shot 2017-08-31 at 12 12 52 pm](https://user-images.githubusercontent.com/1776241/29940977-be8f386c-8e45-11e7-9e03-176655b2e19b.png)

**Comment by troublemagnet** [comment]
I'd like to work on it.

**Comment by adammichaelwood** [comment]
Cool. You may want to coordinate with @mish24 working on #104 since that will likely touch the same template files. (It may not, actually - you'll have to dig in a bit.)

I think IDEALLY, text of the "file issue" notice would be pulled out of rst_epilog and put into a conf.py variable, which can then be sucked into the Jinja template directly. We probably want to style it nice to make it clear it isn't a part of the document.

**Comment by adammichaelwood** [comment]
(Also, see my note on #104 about how to work with template files.)

**Comment by adammichaelwood** [comment]
Closed via #130

**Comment by mish24** [comment]
@adammichaelwood Can you close this?

**Comment by adammichaelwood** [comment]
Oh - I meant to. My mistake.
