### ISSUE TITLE
Correction in Aggregate AWS installation docs

### ISSUE THREAD

**Issue by saadaan** [opendatakit/docs#1030]
Hi,

On this page: https://docs.opendatakit.org/aggregate-aws/, there is a slight correction needed. 

In section CREATE AN EC2 MACHINE, line 8 says: 
>Select Enable in the Auto-assign Public IP dropdown.

This is functionally correct step. However, there is a problem associated with it. By assigning IP like this, AWS assigns you a temporary IP which vanishes if you reboot the machine (a new temp IP is assigned). So this will cause the problem. 

Solution: Instead of assigning IP here in EC2 creation dialogue, you should create the machine without a public IP. Once the machine creation is completed, from the left menu, go to NETWORK & SECURITY > ELASTIC IP, and reserve/allocate an IP there. This IP reservation is permanent for your account (unless you release it). Once allocated, you can then click on the IP and click ASSOCIATE ADDRESS to attach it to your machine (which will be listed in the dropdown). This way, the IP will not vanish on reboot.

**Comment by yanokwa** [comment]
Hi @saadaan! According to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html#lifecycle-differences, IP addresses only changes if you stop and start the instance. Rebooting is fine. That said, I hear you and I've filed a PR at https://github.com/opendatakit/docs/pull/1034 to warn users.
