### ISSUE TITLE
Update Logging enumerator behavior section

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/docs#1031]
We are going to add an option to log new answers in audit file: https://github.com/opendatakit/collect/pull/3072 That will require [Logging enumerator behavior section](https://docs.opendatakit.org/form-audit-log/?highlight=audit#logging-enumerator-behavior) to be updated.

**Comment by lognaturel** [comment]
Document that answers are surrounded by double quotes only if they contain commas. CSV line breaks are NIX `\n`.
