### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by blochmike** [opendatakit/docs#1036]
Hi,

I think there might be an error in https://docs.opendatakit.org/central-install-digital-ocean/ where you has to set up the LetsEncrypt.

The line reads: Change the SSLTYPE line to read: SSLTYPE=letsencrypt. This instructs the server to attempt to obtain a security certificate from the free Let's Encrypt provider.

However, I believe should be: SSL_TYPE=letsencrypt

I'm not a coder, I could be mistaken, but when I run the setup it gave the following warning:
WARNING: The SSL_TYPE variable is not set. Defaulting to a blank string.

Cheers,

M

**Comment by yanokwa** [comment]
Agreed, @blochmike. And I think DOMAIN, SYSADMIN_EMAIL are also not correct.

**Comment by blochmike** [comment]
I followed these instructions today and got my server up and running with my forms very quickly. Super happy. 

Thanks to everyone at opendatakit.org

**Comment by yanokwa** [comment]
Re-opening to make sure we update the docs.
