### ISSUE TITLE
Put page title in/on/near next/prev buttons

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#104]
The Next and Previous buttons at bottom of page would be more helpful if they told you what page was next.

**Comment by mish24** [comment]
@adammichaelwood May I take this up?

**Comment by adammichaelwood** [comment]
Yes please.

This'll involve editing template files.

In case you haven't worked with Sphinx before, a quick outline of the procedure is:

 - Look at the theme source: https://github.com/rtfd/sphinx_rtd_theme/tree/master/sphinx_rtd_theme
 - Find the relevant template file that needs to be edited. 
 - Copy into our `_templates` dir (a local file with name X replaces the built-in file of same name)
 - make edits there

Sphinx uses Jinja templating, which you're probably familiar with.

More details here:
http://www.sphinx-doc.org/en/stable/templating.html

**Comment by mish24** [comment]
@adammichaelwood The page titles are shown when you hover over the button. Shall I display the entire title on the buttons or just a specific length?

**Comment by adammichaelwood** [comment]
I would think the whole title.
But -- try it out and see how it looks.
