### ISSUE TITLE
Central DigitalOcean installation out of date with Marketplace

### ISSUE THREAD

**Issue by seadowg** [opendatakit/docs#1047]
I was installing Central on Digital Ocean and noticed while following https://docs.opendatakit.org/central-install-digital-ocean that Digital Ocean had changed part of their UI labeling - a section marked as "One-click apps" is now marked as "Marketplace". 

Just a small change but as the docs call out the tab by name and have a screenshot it threw me off for a couple of minutes.

**Comment by seadowg** [comment]
As far as I can see to fix this just the text and the screenshot on that page need updating as they were the only references I could find to "One-click apps".

Happy to claim this if that makes sense!

**Comment by yanokwa** [comment]
Whatcha think @issa-tseng?

**Comment by issa-tseng** [comment]
yeah i'll fix it for 0.6 release?

**Comment by seadowg** [comment]
@issa-tseng I'm happy to submit a fix if that's easier for you?

**Comment by issa-tseng** [comment]
yes please @seadowg! very much appreciated. :)
