### ISSUE TITLE
Solve on-page toc problem

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#105]
This is a problem with either Sphinx or the RTD theme. It requires some investigation into whether it is even solvable...

IF you put a table of contents directive on a page other than index, then the sidebar toc includes that toc into it, resulting in duplication of page links in the side bar. This means you can't have on-page TOCs for (for example) a particular subset of docs.

(I was trying to do this with a collect-specific TOC on the first page of collect-guide.)

**Comment by smartyrad** [comment]
@adammichaelwood  For this issue we could use the rubric directive and ensure that the titles are not included in the TOC. Instead, the main TOC will only contain the sub page's TOC. 

References: http://www.sphinx-doc.org/en/stable/markup/para.html#directive-rubric

**Comment by adammichaelwood** [comment]
No, we want real headlines throughout the docs.

**Comment by nadaa** [comment]
Yes, I have noticed this issue also. There should be some way.

**Comment by nadaa** [comment]
If you add (.. contents : :  :local:) on the top of a page, it lists its content.

**Comment by adammichaelwood** [comment]
> If you add (.. contents : : :local:) on the top of a page, it lists its content.

That's true, but that isn't what I wanted to.

**Comment by adammichaelwood** [comment]
I basically found a usable workaround for this while doing the Collect Reorg. Basically, I am using one of two strategies, depending on the desired outcome:

 - "sectional" TOC pages
 - unordered lists of `:doc:` refs
