### ISSUE TITLE
Collect Best Practices / random advice

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#106]
inspired by #6

**Comment by adammichaelwood** [comment]
https://github.com/opendatakit/collect/issues/1306

**Comment by adammichaelwood** [comment]
#54

**Comment by adammichaelwood** [comment]
#61

**Comment by adammichaelwood** [comment]
#92

**Comment by mish24** [comment]
I can add best practices!!

**Comment by adammichaelwood** [comment]
Great! Probably would be good to be a new doc, displayed under the Collect heading in the TOC.
I'm thinking just a series of independent sections, each representing one good idea. We want to make it easy to expand on.

**Comment by adammichaelwood** [comment]
You can do a PR as soon as you have one best practice, then subsequent PRs each time you add a section.

**Comment by mish24** [comment]
And where to place it? In the `Contributing.md` file only right?

**Comment by adammichaelwood** [comment]
No. This is a best practices guide for the Collect App.
So it would be a new doc, `collect-best-practices.rst`.
New doc files sit in the root directory.
Add it to the relevant TOC directive list in `index.rst`
(If you look at how the TOC lists are formatted there, you'll figure it out -- it's pretty straightforward.)

Make sure you actually use the Collect app and write baout best practices that you can verify as working.

If I were you, I would follow the getting started guide all the way through and make sure you have a good handle on general Collect usage.

**Comment by mish24** [comment]
@adammichaelwood I don't understand admin settings menu properly through the links given above. Should I ask about it on forum?

**Comment by adammichaelwood** [comment]
> Should I ask about it on forum?

I think the first line of "hey, how does this thing work?" should be developer slack. It's a better place for ephemeral conversations like that. You're not really having a support issue, you probably just need a quick chat.

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by ankita240796** [comment]
@opendatakit-bot unclaim

**Comment by adammichaelwood** [comment]
We did this!
Best practices should now be put in individual docs and added to the TOC on the collect-best-practices page.
