### ISSUE TITLE
Document settings QR structure

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#107]
From #15

Also document the structure of the QR code for people who want to generate them programmatically - https://forum.opendatakit.org/t/create-my-own-qr-code/7158/2

**Comment by yanokwa** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@opendatakit-bot unclaim

**Comment by mish24** [comment]
@opendatakit-bot claim

**Comment by ayushgangrade** [comment]
@opendatakit-bot claim

**Comment by ayushgangrade** [comment]
@opendatakit-bot unclaim

**Comment by adammichaelwood** [comment]
This claim things has some weirdness to it.

Please ignore the note from the BOT about Zulip, etc.

**Comment by adammichaelwood** [comment]
The QR codes are for bulk configuration of Collect installs. Encoded into the QR is a JSON object with a bunch of app settings.

People want to be able to generate those codes themselves. So we need a doc that shows the JSON object format, explains the compression used, and how to make that into a QR code.

You'll have to research the related issues from the Collect repo, to see how the developer implemented it. You can look into the issue comments and also the relevant code commits.

Let me know if you get stuck and we'll track down the info you need.

This will become a section of the Collect-> Setting and Security Doc (see the QR code section there currently). If it is too long, we'll make it a new doc page.

**Comment by mish24** [comment]
@adammichaelwood Oh okay! I had a look, and it explains what QR codes are, but no steps are described about using them. So I wrote some points for using them through app. Basically divided their usage into 2 parts - using same settings through the app, or through coding. I will add about the json format (programmatically using them) in a while after reading about them. Thanks for the resource :)

**Comment by adammichaelwood** [comment]
So the thing about the QR codes...

If they are generated by the app, another app just scans it and the settings are copied.
(That use case is covered in the current doc.)

If someone is going to generate programmatically, they wont be copying from an install. They just need to know the settings JSON structure.

**Comment by lognaturel** [comment]
@mish24 One other hint -- I think you have Collect building from source. If you run `adb logcat` while running Collect to a connected device/emulator, go to the QR code generating activity and you'll see a log item with the json for the QR code. As @adammichaelwood mentioned, only non-defaults are included so you may have to change some settings to see the format.

**Comment by mish24** [comment]
@lognaturel This solved the only issue that was blocking me! I was spending a lot of time in learning how to use `PyQRCode`. Thanks a lot ma'am :)

**Comment by troublemagnet** [comment]
It has been inactive for quitesome time, may I work on this?
