### ISSUE TITLE
document custom roles

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#108]
th, tc, gesture, formstate

Need a short section in the Writing in Sphinx section of the Contributor's Guide that explains our custom text roles. (Make sure you understand what a text role is in rst/sphinx before doing this.)

th -- table head. USed when referencing a table header cell in the body of text (See, for example, the form widgets doc)
tc -- table cell. used when writing about table cells in the body of text
gesture -- used when describing a touch screen gesture like `double tap`
formstate -- used for identifying the state of a form, such as Saved, Finalized, etc.

**Comment by ayushgangrade** [comment]
Okay I will include both the issues in one PR

**Comment by troublemagnet** [comment]
@opendatakit-bot claim

**Comment by adammichaelwood** [comment]
Be sure to notice in the current contrib guide source file how the existing role documentation is marked up.
