### ISSUE TITLE
Deploy step is broken on CI because openjdk-8-jre-headless is no longer available

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#1085]
~Should be openjdk-11-jre-headless~

Unfortunately s3_website needs jdk8 so we'll need to do something like https://github.com/opendatakit/website/commit/f6c41afe61da627e86c3f2143ef40408e875a836. I'll give @programmablemike a moment to look further into #1084 because then we'll be able to make this change in one place.

**Comment by yanokwa** [comment]
Fixed by #1087
