### ISSUE TITLE
guilabel and menuselection style

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#109]
1. Visual style
2. Some thought about rules of when to use which. (Most cases are obvious, but there's some gray areas.)

**Comment by troublemagnet** [comment]
@adammichaelwood sir what exactly is this issue about?

**Comment by troublemagnet** [comment]
@opendatakit-bot claim

**Comment by adammichaelwood** [comment]
Probably shouldn't claim issues before you understand what they are about.

The roles for `guilabel` and `menuselection` are part of Sphinx. (see the contrib guide and also the sphinx documentation) 

`guilabel` has some styling built into the theme. 
`menuselection` does not.

`menuselection` needs some kind of clear styling, probably similar to `guilabel`

Also, some uses of each are unclear which would be better. (For example, is the home screen of the app a "menu" ?) We need some kind of thought-through clarity about when to use each and why.

I'm certain you can take of the styling issue. So if you'd like to do that you can.
The issue of clarifying usage is something we need to discuss and think about.

**Comment by troublemagnet** [comment]
Apologies for unprofessional behavior sir. I'd work on the styles and will also research about the two options available.

**Comment by adammichaelwood** [comment]
Anyone have an opinion on:

> 2. Some thought about rules of when to use which. (Most cases are obvious, but there's some gray areas.)

**Comment by troublemagnet** [comment]
Sir I don't see how the home screen of app can be "menu" ?

**Comment by adammichaelwood** [comment]
What is a menu other than a listing of items you can select?

**Comment by mish24** [comment]
According to Sphinx guide - wherever there's selection of options, like `Menu A` ---> `Setting B` ----> `Print C`, `menuselection` must be used.

**Comment by adammichaelwood** [comment]
Menu selection is used for any menu. The arrow notation is specifically for nested menus,  but it is not essential to the concept of menu selection.

**Comment by troublemagnet** [comment]
Sir quoting the sphinx guide , 
>  This is used to mark a complete sequence of menu selections, including selecting submenus and choosing a specific operation, or any subsequence of such a sequence. The names of individual selections should be separated by -->.

So sir I think it's usage is to represent a sequence of menu selections.

**Comment by lognaturel** [comment]
@troublemagnet Don't forget that a sequence can have a size of 1! it's not the most interesting sequence but it is a sequence.

**Comment by mish24** [comment]
So, from what I saw in other documentation, `:guilabel:` is used when stating the *topics* or *titles* of the application. Like in Collect, `Saved Forms`, `Edit Saved forms` is a  GUI label. Whereas, the top right corner for settings are menus.

**Comment by troublemagnet** [comment]
Basically from my understanding, we use :menuselection:  when we're guiding the user through menus. So suppose we want them to click on the format menu for viewing all the formatting option, I would use :guilabel: because I'm just asking them to click on a menu and not guiding them through the suboptions or telling them to select a particular option. In other words just clicking on a menu is equivalent to clicking on any other GUI element and hence `guilabel` is a more appropriate choice.

**Comment by lognaturel** [comment]
Well, I could certainly see it either way and I'm sure @adammichaelwood will have some thoughts! Good thing that it will be clarified.

**Comment by adammichaelwood** [comment]
I think the docs could be read either way. Especially since the `guilabel` role includes "menu" in the list of things you can use it for:

> Any label used in the interface should be marked with this role, including button labels, window titles, field names, menu and menu selection names, and even values in selection lists.  
> -- http://www.sphinx-doc.org/en/stable/markup/inline.html#role-guilabel

And, to @troublemagnet's point, the `menuselection` documentation only has examples of a nested menu.

However...
It seems silly (to me, anyway) for some menu item to be marked  as `guilabel` in one instance and `menuselection` in another, which is what would happen if the rule was "Only use menuselection for nested menus."

Moreover... there are two goals that matter more than adherence to someone else's documentation:

 - making our docs as clear as possible to our users.
 - making our docs easy to write.

So here is my thinking based on those goals:

 - As far as I know, there are no places where any label is used twice, in a way that would be confusing. So the differentiation between `menuselection` and `guilabel` is probably not needed to "clear up" such a situation.
 - The current markup styles for `guilabel` and `menuselection` (thanks, @troublemagnet) are equally clear in function. That function being to communicate: "This exact text is on your screen."
 - From a user's point of view, the difference between `guilabel` and `menuselection` is meaningless. 

So, therefore, I suggest the following:

 - adjust `menuselection` styling to match `guilabel`  -- they will both look the same and will therefore communicate the same thing to the users
 - In our writing, we will observe the following rule
    - actual ui text will always receive `guilabel` role unless the text *could reasonably be understood to be part of a menu*
    - if the actual UI text could be understood as a menu, use `menuselection`

Reasons for this: 
 - if any one of us "gets it wrong" in a particular place, the output to the reader will look the same, mitigating the problem.
   - This means, we do our best but we don't worry about it too much
 -  If we do our best to specify one or the other as appropriate, we can style them differently in the future if it becomes clear that we need to do so, with a minimum of correction needed

**Comment by troublemagnet** [comment]
SGTM! 
Makes sense to style them similarly so that the message is conveyed to the user even when we are not clear about which option to use and yeah we can stick to the above convention while documenting.

**Comment by adammichaelwood** [comment]
Great. Can you make that change in the style and issue a PR?

Does `contributing.rst` need to be edited also? 
It's clear to me... but I wrote it, so it might not be clear to others.

**Comment by troublemagnet** [comment]
Yes, I think we should edit it because the whole point of contributing.rst is to tell them about our writing style. Since we've decided on a rule, it should be documented.

**Comment by troublemagnet** [comment]
@adammichaelwood sir I issued a PR and made the styling same. I'll add commits to edit the `contributing.rst` if it is supposed to be done.

**Comment by adammichaelwood** [comment]
Yes, please edit contributing.rst to make the rule above clear.
That PR will close this issue.
