### ISSUE TITLE
Mention expected 400 errors from "Upload ODK Aggregate"

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/docs#11]
Step 17 of the instructions for [installing Aggregate on App Engine (Cloud)](https://opendatakit.org/use/aggregate/#Installing_an_App_Engine_Instance) reads:

> 17. Now click `Upload ODK Aggregate`.
This will spew a very long list of progress messages into the Output window. The `listBackends :` and `deleteBackendBackground :` sections may report "500 Internal Server Error" and Severe errors, and Warnings about the use of Backends, a deprecated feature. This is expected.
>
> Toward the bottom, the `update :` section should not report errors and at the end, a `status : Action Succeeded!` line should be written. This indicates that the upload completed successfully.
>
> An example of the scrolling progress messages produced by a successful upload is [here](https://opendatakit.org/wp-content/uploads/Apr2016-GoogleCloud/exampleUploadScriptOutput.txt).

I thought it was helpful that the instructions list the errors you are expected to encounter, for example, "500 Internal Server Error". I encountered several "400 Bad Request" errors, which I initially thought indicated a problem with my installation, but after looking at the [example log](https://opendatakit.org/wp-content/uploads/Apr2016-GoogleCloud/exampleUploadScriptOutput.txt) mentioned in the instructions, it looks like those are normal. I'd recommend explicitly mentioning those 400 errors in the instructions so that it's clear they're expected.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
