### ISSUE TITLE
Document audio, video media and autoplay

### ISSUE THREAD

**Issue by seadowg** [opendatakit/docs#1112]
There are some examples of using audio and video media in forms as part of "Form Styling" and also with specific examples for "Select widgets" but there isn't any thorough documentation on using audio/video in forms. Things I think we should cover are:

* How to put audio/video in at the XLSForm stage
* How audio/video gets presented in Collect
* How to have audio and video autplayed (and how it behaves in Collect)

**Comment by seadowg** [comment]
@opendatakit-bot claim

**Comment by seadowg** [comment]
@issa-tseng happy for me to start on this?

**Comment by issa-tseng** [comment]
hi! did you mean to tag me? i'm not sure i know anything about this! :)

**Comment by lognaturel** [comment]
I think this would be great to get in with the Collect v1.24 release, @seadowg!

**Comment by seadowg** [comment]
@issa-tseng ooooops. Meant to tag @lognaturel but somehow autocomplete failed be very badly. Sorry for the ping!

**Comment by seadowg** [comment]
@opendatakit-bot claim
