### ISSUE TITLE
Collect Jump button

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#112]

**Comment by tanvibhakta** [comment]
What is this? :smile:

**Comment by troublemagnet** [comment]
@adammichaelwood Sir Can you elaborate on what is to be done as a part of this issue?

**Comment by lognaturel** [comment]
I'm sorry, I forgot to search and filed a duplicate at #186! 😳 Since that one has been claimed, let's close this one.

**Comment by adammichaelwood** [comment]
> I'm sorry, I forgot to search and filed a duplicate at #186!

That's my fault too, for not writing a description.
Before we had all these awesome contributors from Outreachy, I was just in my own little world, filing issues all for myself...
