### ISSUE TITLE
Form states

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#113]

**Comment by ayushgangrade** [comment]
@adammichaelwood If this is free I would like to work on this :)

**Comment by adammichaelwood** [comment]
There's no description because it's a minor thing I just needed to remind myself to add when I had a minute. But I'd love for you to take care of it.

1)

In `_static/css/custom.css`

```
.formstate {
 font-style: italic;
}
```
2)

go through the Collect guide pages and make sure all references to form states (Saved, Finalized, Deleted) look like `:formstate:\`Finalized\``

3)

Add a mention to the formstate text role in the Writing in Sphinx section of the Contributor's Guide.

**Comment by troublemagnet** [comment]
@opendatakit-bot claim

**Comment by troublemagnet** [comment]
@adammichaelwood Sir the user who initially showed interest in this issue seems to have deleted his/her account, Should I work on it and #108?

**Comment by adammichaelwood** [comment]
That would be fine. These are both small and can be included in a single PR.
