### ISSUE TITLE
no "step 9" on referenced page (ODK Central installation)

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/docs#1131]
In
https://github.com/opendatakit/docs/blob/master/odk1-src/central-install.rst
In the last paragraph
> We would still recommend reviewing the instructions we've provided for DigitalOcean starting from step 9.

But it doesn't seem like the steps are numbered anymore. There is not step 9 on the linked page.

**Comment by lognaturel** [comment]
Ooh, that's right! Maybe we should link to https://docs.opendatakit.org/central-install-digital-ocean/#installing-odk-central? @issa-tseng?

**Comment by issa-tseng** [comment]
ah shoot. :(
yeah, i guess that's right.
we also reference "step 15" here: https://docs.opendatakit.org/central-command-line/#creating-a-web-user-by-command-line

**Comment by issa-tseng** [comment]
.
