### ISSUE TITLE
Likert documentation

### ISSUE THREAD

**Issue by shouryaj** [opendatakit/docs#1135]
Documentation for issue #1272 in ODK Collect 

https://github.com/opendatakit/collect/issues/1272

**Comment by lognaturel** [comment]
Ah, I see why @grzesiek2010 ended up with a duplicate. @shouryaj, please make sure to claim an issue you're working on with `@opendatakit-bot claim` and put `Closes #<issue number` at the top of a PR you submit so it's clear someone is working on it!

**Comment by shouryaj** [comment]
Oh oops! My bad will be more careful in the future!
