### ISSUE TITLE
Main Menu explanation

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#114]

**Comment by lognaturel** [comment]
Specifically, clarify what View Sent Form is for - https://forum.opendatakit.org/t/deleted-submission-remains-in-view-sent-form/9669

**Comment by mish24** [comment]
@lognaturel Can I take this up?

**Comment by adammichaelwood** [comment]
(I bet she'll say yes.)

The idea here was just to be real clear on each one. They are mostly self explanatory, but it would be helpful to say that the user will see (for example) Sent forms, but not saved one. Or that they'll see deleted ones but not be able to edit them. Etc.

**Comment by mish24** [comment]
@adammichaelwood It was clear to me when I was reading it for the first time. But I will add extra data :)

**Comment by mish24** [comment]
![screenshot from 2017-09-10 06-17-01](https://user-images.githubusercontent.com/24610197/30246651-b5910284-95ef-11e7-8c70-a1eea8e749a1.png)

@adammichaelwood Please see the highlighted text. I'm a bit confused. The forms (saved and finalized both) are viewable all the time right?

**Comment by adammichaelwood** [comment]
I thought it was clear too (I wrote it!)
But it isn't all in one place.

@ln wanted a short section in the collect guide that just explained each item in the main menu, and what one should expect to see when opening it. (For example, some lists show saved but not sent, some show deleted, while others don't, etc.)

**Comment by mish24** [comment]
@adammichaelwood What about sent forms? They are viewable even after they're deleted right?
