### ISSUE TITLE
Theme error: sphinx_rtd_theme is no longer a hard dependency since version 1.4.0.

### ISSUE THREAD

**Issue by ronna** [opendatakit/docs#118]
On Windows 10 when building the docs locally:

C:\Users\ronald\Documents\GitHub\docs>sphinx-build -b html . build
Running Sphinx v1.6.1
making output directory...
loading pickled environment... not yet created

Theme error:
sphinx_rtd_theme is no longer a hard dependency since version 1.4.0. Please install it manually.(pip install sphinx_rtd_theme)

C:\Users\ronald\Documents\GitHub\docs>

May be we should add the sphinx_rtd_theme to the requirements file. Not sure what effect it has on *nix platform

**Comment by adammichaelwood** [comment]
> May be we should add the sphinx_rtd_theme to the requirements file

It already is there. Check your local requirements.txt file.
You might have missed pulling in changes since PR #90 
or, you may have got the changes but not re-run `pip install -r requirements.txt`

**Comment by ronna** [comment]
@adammichaelwood 

You are right, sorry for the noise, I only checked open issues before creating the issue. I am on a bad connection and latest changes were not pulled.

Please close the issue

**Comment by adammichaelwood** [comment]
No problem.
Most of my own errors come from forgetting to pull in from upstream.

**Comment by afkHub** [comment]
`pip3 install sphinx sphinx_rtd_theme`
I had the same problem. It is solved when I installed like this
