### ISSUE TITLE
Explain how Sphinx templating and theming works, for contributors guide

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#119]
Need a reference so that anyone working on templating or theming issues has clear information about how the theme is structured. Should link to relevant Jinja and Sphinx docs.

**Comment by smartyrad** [comment]
hi @adammichaelwood , I wish to take up this issue. May I?

**Comment by mish24** [comment]
@adammichaelwood There are already so many concepts explained with regards to Sphinx, since this is not related to the project, maybe separating the entire `Sphinx-tutorial` section will prove a better option, or providing links to tutorials?

**Comment by adammichaelwood** [comment]
> I wish to take up this issue. May I?

Sure.

Basically, we want to provide enough info that someone working on issues like #103 or #104 would know be able to get off on the right foot. An explanation of what theme we use (rtfd/rtd_theme), how template overriding works, links to relevant docs, etc.

(Maybe talk to the people working on #103 and #104 to see what they have had to learn, what issues were non-obvious, etc...)

**Comment by adammichaelwood** [comment]
> maybe separating the entire Sphinx-tutorial section will prove a better option, 

I'm not completely sure what your suggestion is. However, I have been thinking we should break the `contributing.md` into separate docs. 

What is there currently could be three:

 -  Intro to Contributing
 - Tooling
 - Writing in Sphinx

This issue would then be a new doc, Sphinx Templating, or perhaps part of a larger *developing the docs* document. 

I'll open an issue to discuss.

**Comment by smartyrad** [comment]
@adammichaelwood  This makes sense. So, we can design it such that the intro to contributing page contains all the information for a user to be able to get his dev environment setup. The rest of the info/details like working with sphinx etc can be part of a new doc(s).

**Comment by adammichaelwood** [comment]
@smartyrad 

I noticed on your fork that you added the info about Sphinx into index.rst
Index.rst is the front page of the docs site.

The Sphinx templating guide should be its own new doc. We'll add it to the Table of Contents in the Contributing section.

**Comment by adammichaelwood** [comment]
Couple other issues with the in progress commit:

 - please don't line break at 80 chars. line break at paragraphs only (that is mentioned in the contributor's guide)
 - we don't need a long explanation of the benefits of sphinx or static site generators.
 - check your title formatting (please make sure you have read the "writing in Sphinx" section of the contributor's guide

The info people need is:

 - we use the rtd_theme (link to where that is)
 - the original template files can be found (way deep in the virtualenv directory, or in the rtd_theme gh repo)
 - to change the theme, override the template by copying the relevant template file, and then working on it
 - a bit about blocks and extending template files
 - where custom.css and custom.js are
 - where to learn more about jinja templating and sphinx development

**Comment by smartyrad** [comment]
@adammichaelwood  Sorry for that misleading commit :). I was trying out some stuff and hence made that commit .

I have created a new PR with all the changes. Kindly do check it out here https://github.com/opendatakit/docs/pull/133

**Comment by adammichaelwood** [comment]
I am closing this PR, then.
Let me know when #133 is ready for review.
And please add "Closes" and the number it address, so the issue will auto-close when the PR is merged.
