### ISSUE TITLE
Split contributor's guide into separate docs

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#120]
from discussion on #119 

What is there currently could be three:

Intro to Contributing
Tooling
Writing in Sphinx

and then, potentially a new section: Developing the Docs, for people working directly on the tools, theming, and deployment

This would make it easier to add a style guide also, which we should do at some point. (Probably sooner rather than later.)

**Comment by mish24** [comment]
Intro to contributing:
1. What to work on
2. Avoid doing the following mistakes section
3. Best Practices 
  a. For Issue Reporting
  b. For Pull Requests
4. Coding Style and Standards
5. Git workflow

**Comment by tanvibhakta** [comment]
If @mish24 isn't actively working on this, I would love to.

**Comment by mish24** [comment]
@tanvibhakta I'll work on this.

**Comment by adammichaelwood** [comment]
I assigned myself and am going to work on it. 
I have particular ideas about the contributors guide.
