### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#121]
We're going to need one.

**Comment by tanvibhakta** [comment]
I agree. One major thing which needs explaining is how multilevel headers are represented. There doesn't seem to be a clear indicator of that as of now.

**Comment by adammichaelwood** [comment]
> how multilevel headers are represented
What do you mean?

**Comment by nadaa** [comment]
@adammichaelwood , I will work on that if possible.
I need to know what you expect from this guide, and how it differs from Sphinx guide in the contributing doc?
Thanks

**Comment by adammichaelwood** [comment]
This is not up for claiming. It is a writing style guide, which I will be working on.

**Comment by adammichaelwood** [comment]
I think this thread would be a good place to keep random style guide items as they come up. These will all make it into the formal style guide, but for now this can be a quick reference and also a reminder for when that guide is written.

**Comment by adammichaelwood** [comment]
AMERICAN SPELLING

Whenever an English word has multiple spellings (color, colour; gray, grey), the American spelling is preferred.

Notes:

 - This is for consistency, not because we think American English is better. 
 - Given the international nature of of the project, the ubiquity of locale-specific spell checkers, and the fact that even the lead maintainer of this repo is a terrible typist, we're all going to be forgiving and gracious about this whenever inconsistencies crop up.

**Comment by adammichaelwood** [comment]
GESTURES

When describing touch gestures, use the `:gesture:` text role and do not capitalize them.

```
You can :gesture:`swipe right` if you really like this project.
```

**Comment by adammichaelwood** [comment]
XML / HTML

`<tag>` --- The actual typed code is a *tag*

`<thing>Stuff</thing>` --- The logical unit of a document is an *element*

`<elementName attribute="value">Content</elementName>` --- the token used for the tags is what names the element as a whole. But the whole thing is an element, not a tag. An element has an attribute; a tag does not have an attribute. An element's attribute has a value. An element has content. The content might include other elements. Tags are not nested; elements are nested.
