### ISSUE TITLE
Make the footer buttons responsive

### ISSUE THREAD

**Issue by mish24** [opendatakit/docs#129]
![imp](https://user-images.githubusercontent.com/24610197/30250575-3e33d5f8-9640-11e7-8505-1c3ff7183cba.png)

The width of the footer buttons should become 100% and they must be stacked on each other when the screen size is reduced.

**Comment by adammichaelwood** [comment]
Additional requirements:

 - a bit of margin between the two buttons when vertically stacked
 - the previous button should be above the next button
 - this should be done responsively in CSS, without javascript

**Comment by ankita240796** [comment]
I would like to work on this, may I?

**Comment by adammichaelwood** [comment]
If you know a bit about responsive CSS, yes please.

Custom styles go in `_static/css/custom.css` 

Be sure to comment your code.

**Comment by adammichaelwood** [comment]
closed via #152
