### ISSUE TITLE
[contributing.rst] Update the instruction to view documentation in web browser with the usage of python3.

### ISSUE THREAD

**Issue by troublemagnet** [opendatakit/docs#132]
![tbppr](https://user-images.githubusercontent.com/28952053/30263572-0bd98482-96f3-11e7-9e53-9e53fb8f4136.png)
Update the build instructions with the usage of python3. Using python gives the `No module named http
` error.

**Comment by mish24** [comment]
The installation process has specified while creating the virtual environment that Python 3 must be used.

**Comment by troublemagnet** [comment]
Oh sorry, my bad

**Comment by adammichaelwood** [comment]
Once you create a virtual environment with Python 3, the `python` command uses the python3 interpreter.
