### ISSUE TITLE
Briefcase Guide

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#136]
A new doc or set of docs on using Briefcase.

(These would be added as **new** toc directive to `index.rst`, creating a new section of docs.)

A starting place is the existing/old documentation:
https://opendatakit.org/use/briefcase/

Working on this requires following existing docs:

 - DLing and installing Briefcase, 
 - using it as specified in the existing docs,
 - experimenting with it to make sure you have clear understanding
 - bringing the old text into the repo and correcting it and updating it for clarity and to reflect current actual uses
 - adding relevant information from other Briefcase related issues and support forum threads

**Comment by troublemagnet** [comment]
Sir I'd like to work on this.

**Comment by adammichaelwood** [comment]
Please get through these steps:

> - DLing and installing Briefcase,
> - using it as specified in the existing docs,
> - experimenting with it to make sure you have clear understanding

And also make you have gone through the main [getting started guide](http://docs.opendatakit.org/getting-started/) and have a decent understanding of Collect.

When you have done that, let me know if you want to work on the Briefcase doc.
