### ISSUE TITLE
Render markup out of conf.py

### ISSUE THREAD

**Issue by troublemagnet** [opendatakit/docs#141]
confy.py at the moment contains a lot of variables to display the footer text. Goal is to have a variable that renders the markup.

**Comment by troublemagnet** [comment]
I'd like to take it up.

**Comment by adammichaelwood** [comment]
Do some research on Sphinx documentation/forums/etc first.

I've run into this problem before:
I wanted to include links in the license/copyright statement, and markup doesn't work right. 
Someone, somewhere must have solved it. I don't want to go down some wild coding goose chase. There must be a setting or a simple fix or something, somewhere....

**Comment by troublemagnet** [comment]
![prooof](https://user-images.githubusercontent.com/28952053/30316125-d770704e-97c3-11e7-8816-3d8bda410b56.png)
Sir the official documentation seems to be using a method similar to ours.

**Comment by adammichaelwood** [comment]
That is very interesting.
Ok, I think we should leave this issue alone for now.
It's working fine and is extremely low priority.

(Sidenote, for future reference: Including a screen shot is not a good way to reference documentation, or other information. If I was on a phone, or using assistive technology, that would be unreadable. It was fine for me today, and I could read it, but it is not a good practice in general.)
