### ISSUE TITLE
Add a pull request template

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#144]
We've been using pull request templates on some of the other ODK tools and they have been really helpful for remembering to close issues, to actually try out the changes, explain why certain decisions were made, etc. For example, Collect's is [here](https://github.com/opendatakit/collect/blob/master/.github/PULL_REQUEST_TEMPLATE.md). Having the template in place has helped a lot with review.

@adammichaelwood what do you think of including a template here?

**Comment by adammichaelwood** [comment]
I always am a little annoyed by templates. "Ugh - do I have to fill out all these items for my three typo fixes? How annoying...."

But... I think you are right and that they are useful.

**Comment by adammichaelwood** [comment]
opendatakitbot-claim

**Comment by adammichaelwood** [comment]
@opendatakitbot-claim

**Comment by adammichaelwood** [comment]
@opendatakit-bot claim
