### ISSUE TITLE
How to include video in docs

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#148]
Section should be added to contributor guide, near/after the section on adding images. Show markup, where to put the vid, and also how to use `adb` to take a vid from collect. Also, note that videos inside the docs should be less than a minute in length.

**Comment by mish24** [comment]
@adammichaelwood I can add about videos in `adb` in section right now. I just learned that.
Plus if it's okay I can add the additional contents too.

**Comment by adammichaelwood** [comment]
I was thinking @troublemagnet should do this, since she just worked on the vid directory stuff.

**Comment by troublemagnet** [comment]
Sure, I'll be able to do it.

**Comment by mish24** [comment]
Oh I already started working on it

**Comment by mish24** [comment]
@adammichaelwood Should this include embedding videos from YouTube?

**Comment by adammichaelwood** [comment]
> Oh I already started working on it

**Comment by adammichaelwood** [comment]
> Oh I already started working on it

You've got several other things you are working on, so let's give @troublemagnet the chance to work on this.

**Comment by adammichaelwood** [comment]
> Should this include embedding videos from YouTube?

I can't think of a reason we would want to encourage doing that.

**Comment by mish24** [comment]
@adammichaelwood Yes. I'll leave this issue
