### ISSUE TITLE
Test README build before submitting changes

### ISSUE THREAD

**Issue by mish24** [opendatakit/docs#149]
I think a script can be added to check whether README build is successful before submitting a PR. This is easy, and implements *Style guide testing*. @adammichaelwood What do you think?

**Comment by mish24** [comment]
It's always a markdown file so styling in this case is fixed.

**Comment by mish24** [comment]
I can make a pre commit hook to run all these tests, starting with this one. @adammichaelwood @yanokwa @lognaturel This will include tests for checking commit messages (if that is defined in future)

**Comment by adammichaelwood** [comment]
I don't understand what you want to accomplish here.

**Comment by adammichaelwood** [comment]
This doesn't really implement style linting on the docs. It's just a tool for checking how the README is going to look. And the README, while currently in need of an update, doesn't change often enough for that to be really needed.

**Comment by mish24** [comment]
@adammichaelwood Yes. Even I thought this will not be that useful. What about commit message syntax? Is it required to test those?

**Comment by adammichaelwood** [comment]
No I don't think that would be helpful.

What we want to do is implement proselint, or something like it, for style checks on the actual documentation writing.
