### ISSUE TITLE
Bulk configuration through QR codes

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#15]
https://github.com/opendatakit/collect/issues/781

https://opendatakit.org/2017/06/configure-collect-on-many-devices-with-qr-codes/

**Comment by lognaturel** [comment]
Also document the structure of the QR code for people who want to generate them programmatically - https://forum.opendatakit.org/t/create-my-own-qr-code/7158/2?u=ln

**Comment by adammichaelwood** [comment]
> Also document the structure of the QR code for people who want to generate them programmatically 

moving this to a separate issue.
