### ISSUE TITLE
In getting started guide, describe how to get help

### ISSUE THREAD

**Issue by troublemagnet** [opendatakit/docs#160]

**Comment by mish24** [comment]
@troublemagnet I also thought about adding this info in docs. 
https://github.com/opendatakit/docs/pull/115 ---> this was the discussion.

**Comment by adammichaelwood** [comment]
Yeah. I'm a little concerned about trying to explain advanced git usage, for two reasons:

 - I don't want new contributors to get confused or overwhelmed
 - existing git documentation covers this better than probably we could

Given the size of our docs contributor community, I think we can probably handle answering questions about this on slack when it comes up, and pointing people to the git docs. Perhaps in future we can add a "What to do if you mess up your git repo" document or section.

**Comment by lognaturel** [comment]
I agree that we don't want to duplicate `git` documentation! @adammichaelwood how would you feel about adding a note in the contribution guide that explicitly encourages anyone who gets stuck or in a bad state to join #docs-code and ask there?

**Comment by adammichaelwood** [comment]
That's a great idea.

**Comment by troublemagnet** [comment]
> That's a great idea.
Yes, that's true. Should I work on it?

**Comment by troublemagnet** [comment]
> That's a great idea. 

That's true. May I work on it?

**Comment by adammichaelwood** [comment]
Sure.

**Comment by troublemagnet** [comment]
> I agree that we don't want to duplicate git documentation! @adammichaelwood how would you feel about adding a note in the contribution guide that explicitly encourages anyone who gets stuck or in a bad state to join #docs-code and ask there?

@adammichaelwood Sir your PR covers this right?

**Comment by adammichaelwood** [comment]
I think the contributor tips probably covers it. 
Anyone else have an opinion?
