### ISSUE TITLE
Windows without Cygwin

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#161]
Windows 10. (I'm assuming Linux subsystem.)

The following would probably be useful:

 - Amend the the note about Windows in the main contributor guide
    - While you are working on that, add a link to the Cygwin doc
 - Put a note at the top of the cygwin doc

**Comment by Divya063** [comment]
@adammichaelwood I just used command prompt which comes pre-installed on Windows

**Comment by Divya063** [comment]
@opendatakit-bot Claim

**Comment by Divya063** [comment]
@adammichaelwood Can I work on this issue?

**Comment by adammichaelwood** [comment]
Yes, that's why I opened it.

BEfore you jump in - can you describe your process. 
You said you didn't use Linux subsystem. Did you adapt the commands to powershell? Use gitbash?

**Comment by Divya063** [comment]
Currently Windows supports powershell ,cmd(command prompt) as well as git bash. Command prompt has a user-friendly command structure and that's why I use it.By default some Windows systems are coming with powershell,Preferences can be changed  by opening Settings > Personalization > Taskbar, and turning ‘Replace Command Prompt with Windows PowerShell in the menu when I right-click the Start button or press Windows key+X’ to Off.

**Comment by Divya063** [comment]
@adammichaelwood  all the commands are basically same with the ones used in Linux except the commands used in creating virtual environment

**Comment by adammichaelwood** [comment]
Sounds good.

Which organization approach makes more sense to you?

 - insert these details in existing contributors guide
 - combine this with the cygwin page, so there's a windows document with two sections
 - new document

**Comment by Divya063** [comment]
@adammichaelwood I think inserting the details in existing contributors guide would be good as many commands are repetitive (same in Linux and windows).In those areas where commands are different we can do this for instance
Taking this case
> inside that odk directory, create a python3 virtualenv.

`$ virtualenv -p python3 odkenv`

On windows  run the venv module as a script with the directory path:
 `>C:\python36\python -m venv odkenv`

**Comment by adammichaelwood** [comment]
Great. Let's go with that.

**Comment by nadaa** [comment]
@Divya063, please try to repeat the previous steps as described. You then add any thing you find helpful. 
"C:\python36\python -m venv odkenv" can be added as an extra way to build a virtualenv. 

I think specifying the full path in the prompt  is confusing, In your case, you tell people to go to C:\python36, which is not necessary.

**Comment by Divya063** [comment]
@nadaa I was just giving an instance

**Comment by nadaa** [comment]
It is fine @Divya063 :).
