### ISSUE TITLE
Differences between Aggregate and Briefcase

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/docs#17]
The practical difference between Aggregate and Briefcase is often clear — for example, many features are available in one but not the other — but I've struggled with the conceptual difference. Where does Aggregate end and Briefcase begin? For example, when do you export data from Aggregate vs. export from Briefcase?

I discussed with Yaw and Hélène, who described the following differences and suggested I create an issue in the docs repo:
* Briefcase is good for offline use, for when there's no need for a server. Briefcase is often enough for smaller projects. However, note that Aggregate can also be used offline and locally.
* Briefcase can be used to back up all forms and submissions on Aggregate. In particular, Briefcase's command line interface makes this easier.
* Briefcase is needed to transfer data between Aggregate installs.
* Briefcase is required to decrypt any encrypted submissions.

**Comment by troublemagnet** [comment]
I'd like to work on this.

**Comment by adammichaelwood** [comment]
I think this needs to wait until at least the Briefcase documentation has been added.

**Comment by ankita240796** [comment]
May I take this up?

**Comment by adammichaelwood** [comment]
Yes. I would add it as another document in the new Briefcase TOC.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
