### ISSUE TITLE
Pull in, edit/correct existing encrypted forms doc

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#170]
https://opendatakit.org/help/encrypted-forms/

This text would be a good start for a doc to add to our repo.

The person working on it needs to actually follow the entire procedure laid out in the document, to see what works, what doesn't what needs to be changed, etc.

Then:

 - add this as a new doc page
 - implement rst markup throughout (this will likely also involve re-linking links to pages in the new doc
 - edit content - fix whatever is wrong or incomplete
 - figure out best place in the TOCs

**Comment by mish24** [comment]
@adammichaelwood Some part is common for Collect and Aggregate. There has to be a part which explains how these form encryption are useful everywhere explicitly. Briefcase has other methods for encrypting forms, which isn't needed in Collect and Aggregate specific sections

**Comment by Divya063** [comment]
@opendatakit-bot claim

**Comment by adammichaelwood** [comment]
Maybe a new toc tree for "integration"

**Comment by Divya063** [comment]
@adammichaelwood  @mish24 is right also, the text is not clear enough to explain how to use XLSForm, Collect, Aggregate and Briefcase altogether.The installation steps are working fine and well explained.

**Comment by Divya063** [comment]
@adammichaelwood  Is this issue #57 in progress? I was thinking to link Installation guide of ODK Aggregate with the Encrypted Forms
