### ISSUE TITLE
Document advanced use of external apps

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#18]
Custom error messages and `field-list`s -- opendatakit/collect#129 and <strike>https://opendatakit.org/help/form-design/external-apps/</strike> (done)

**Comment by mish24** [comment]
@opendatakit-bot claim

**Comment by mish24** [comment]
@lognaturel I can add a new doc for the use of external apps, I tried something which manipulated forms from source code. Are there any specific points to keep in mind? Also, just to be sure, does this require a doc which explains forms as well? @adammichaelwood

**Comment by adammichaelwood** [comment]
Yeah, as i mentioned in another issue, an intro to form design would be a good page to have.

**Comment by adammichaelwood** [comment]
This issue was created before the two external-app pages were created.
Is there anything not mentioned in those? Or can we close this issue? @lognaturel

**Comment by lognaturel** [comment]
The info about customizing the button and message has not been added yet. The other doc can be deprecated.

**Comment by adammichaelwood** [comment]
Closing this and opening new issue on single item.
