### ISSUE TITLE
Form Design Workarounds and Tips

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#181]
https://opendatakit.org/help/form-design/workarounds/

This document needs to be brought into the current repo. Along the way, the information in it should be verified directly. Edits for clarity/typos/etc. should be done as well.

**Comment by mish24** [comment]
@adammichaelwood Can I work on this? I'll test it along the way as well.

**Comment by adammichaelwood** [comment]
> isn't a doc for XLSForm required for this?

I think our current thinking is that we don't want to duplicate the xlsform.org site's documentation, but rather point people to it.

It would probably be helpful to have an *Intro to Form Design* doc, that heads up the FORM DESIGN section, with links to the xlsform.org site. 

That could start by pulling in the existing form design pge from opendatakit.org. (You could file an issue and work on it.... but make sure you're not sitting on too many claimed, open issues.)

**Comment by lognaturel** [comment]
For the workaround described in the "repeat-groups are not respecting the jr:count setting after a change" section, the form from [here](https://github.com/opendatakit/collect/issues/868#issuecomment-302466153) should be included to illustrate the technique.

**Comment by mish24** [comment]
@adammichaelwood I am done writing the base Form Design doc, so I'll start working for this now!
@opendatakit-bot claim.

**Comment by adammichaelwood** [comment]
All of these items have either been taken care of, or new issues have been added to address them.
