### ISSUE TITLE
Jumping between questions while filling a form

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#186]
While filling a form, an enumerator can jump between questions or skip to the beginning or end by tapping on the arrow icon at the top of the screen. The icon is not currently all that intuitive so I think including a screenshot would be worthwhile.

Describe what shows up in the jump menu, especially when repeats are involved. This is not obvious as the conversation in https://forum.opendatakit.org/t/looped-group-broken/9946 demonstrates.

I think this should go in the [Filling out forms](http://docs.opendatakit.org/collect-forms/#filling-out-forms) section as a subsection.

**Comment by mish24** [comment]
@opendatakit-bot claim

**Comment by mish24** [comment]
@lognaturel Understood! I'll add this
