### ISSUE TITLE
Fix bad variable naming in conf.py related to footer text.

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#191]
The variables names introduced in #188 and #130 are bad practice:
prevar1, prevar2, prevar4, link1, link2, hyper1, hyper2.... yikes.

If you need a quick lesson on variable naming:
http://wiki.c2.com/?GoodVariableNames

But, of course, keep to PEP8 for casing/format:
https://www.python.org/dev/peps/pep-0008/#naming-conventions

@ankita240796 or @troublemagnet should solve this, since they created the problem.
(First one to claim it gets to do it.)

**Comment by ankita240796** [comment]
@opendatakit-bot claim
