### ISSUE TITLE
Fix contri_guide link in conf.py

### ISSUE THREAD

**Issue by ankita240796** [opendatakit/docs#195]
![image](https://user-images.githubusercontent.com/15226041/30774940-ebace7b2-a0a7-11e7-9abe-91e950ae23e8.jpg)

**Comment by ankita240796** [comment]
I'd like to take this up. Do we need a link in this part?

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by mish24** [comment]
@ankita240796 Hey! Which specific link are you talking about in `conf.py`? No links are specified yet and everything is commented.

**Comment by ankita240796** [comment]
@mish24 The footer section commented as 'At bottom of every document' has a variable declaration link3=contributing.html.
