### ISSUE TITLE
Form Design Guide

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#20]
https://opendatakit.org/help/form-design/
and especially this:
 https://opendatakit.org/help/form-design/examples/

But with Excel-based on examples as well as XML,
and links to the spec., etc.

**Comment by ronna** [comment]
@adammichaelwood 
we could borrow or reference the Nafundi form design tips
https://nafundi.com/blog/posts/odk-form-design-tips-that-improve-data-quality/
https://gumroad.com/l/odk-form-design-tips

We can also include the "All Widgets" form as an example

**Comment by lognaturel** [comment]
@yanokwa and I are happy for those design tips to be modified however is appropriate to become part of official docs.

**Comment by adammichaelwood** [comment]
I think this has basically happened with the work done on the forms section and new docs (some currently pending in PRs), though perhaps not as originally conceived. 
I'm closing this now, and if anyone thinks a specific piece of documentation should be added, new, more specific issues can be opened.
