### ISSUE TITLE
Adding a scrollbar on toc

### ISSUE THREAD

**Issue by nadaa** [opendatakit/docs#203]
I find it difficult to navigate toc using the right scrollbar. I think it will be helpful to add one on the sidebar.
What do you think?

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by lognaturel** [comment]
@nadaa I see what you mean! It looks like the sidebar does scroll independently when a scroll gesture is used but there is no visible scrollbar.

@ankita240796 it would be good to get some feedback from @adammichaelwood before adding this.

Here's an advanced `opendatakit-bot` tip -- you can label issues using the `label` command. For example, in this case, you could have used 

opendatakit-bot label discussion

to label the issue as a conversation. All bot commands can be found at https://github.com/opendatakit/zulipbot/blob/master/src/config.js

**Comment by lognaturel** [comment]
@opendatakit-bot label discussion

**Comment by lognaturel** [comment]
@opendatakit-bot label discussion

**Comment by lognaturel** [comment]
@opendatakit-bot label "discussion"

**Comment by ankita240796** [comment]
I got that @lognaturel. Thanks !

**Comment by nadaa** [comment]
@lognaturel, thanks for sharing bot commands, first time to know about them.

**Comment by adammichaelwood** [comment]
@ankita240796 -- yes, please don't claim issues unless they have been discussed.

As @lognaturel mentioned -- the sidebar does, in fact, scroll.
@nadaa does knowing that make it easier to navigate?

**Comment by ankita240796** [comment]
@adammichaelwood I'll be careful about that in future.

**Comment by nadaa** [comment]
@adammichaelwood, I prefer to have a scrollbar on the sidebar. It will help navigating once the toc gets bigger.

**Comment by adammichaelwood** [comment]
i'd be open to someone (@ankita240796? @nadaa?) trying out a solution and letting us see what it might look like and how much modification this requires. It might be little more than a couple lines of CSS.

**Comment by ankita240796** [comment]
@adammichaelwood I'll try doing that. Thanks!

**Comment by troublemagnet** [comment]
@adammichaelwood  now that TOC has grown, it has become difficult to navigate through the table of contents. I guess we should have a scroll bar.

**Comment by adammichaelwood** [comment]
there is a scrollbar, you just can't see it. just like on the page as a whole

**Comment by troublemagnet** [comment]
@adammichaelwood true sir but in the absence of a scroll bar not everyone will know that there's more content in the TOC.

**Comment by adammichaelwood** [comment]
I'm closing issue because there really *is* a scroll bar there. Also the TOC is getting a lot smaller with the next several rounds of sectional re-organization.
