### ISSUE TITLE
Fix build command in docs; mention `./b.sh`

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#204]
The `sphinx-build` command shown in the docs is not consistent with what we do when we deploy.

The command should be:

```
sphinx-build -b dirhtml . build
```

---

It would be good to add a `tip` in that section to use `./b.sh` 
This is a convenience/utility script I wrote that saves typing.
In the future, it will become the canonical build script (as we incorporate testing, etc., into the docs) so it would be good to get used to it now. 
And it saves typing.

**Comment by troublemagnet** [comment]
@opendatakit-bot  claim

**Comment by adammichaelwood** [comment]
BTW - i just updated the description, because (hilariously) I typed the command wong the first time.
It is correct now.
