### ISSUE TITLE
Create Android desktop shortcut to launch specific form

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#210]
https://forum.opendatakit.org/t/opening-a-form-automatically-when-collect-starts/1649 gives basic instructions. They should be verified with latest Android versions. Collect now supports 4.1 and above so I don't think we need instructions for older devices.

http://www.samsung.com/uk/support/skp/faq/1057750 has some good background on Widgets.

**Comment by Divya063** [comment]
@lognaturel This will work on all android versions higher than 4.1

**Comment by adammichaelwood** [comment]
This is a good item for #106

**Comment by ankita240796** [comment]
@opendatakit-bot claim
