### ISSUE TITLE
Update Briefcase installation guide to recommend Java 8

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#212]
Java 1.7 was deprecated on April 2015 and so it does not receive security updates. It's probably irresponsible for us to target Java 1.7 and yet the Briefcase installation guide says to use Java 7. It should use Java 8!

**Comment by ankita240796** [comment]
@opendatakit bot claim

**Comment by yanokwa** [comment]
@ankita240796 You might have to write a new comment with `@opendatakit-bot claim` because your original comment was missing a hypen. I don't think edits will work.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
