### ISSUE TITLE
Contributor Guide

### ISSUE THREAD

**Issue by ronna** [opendatakit/docs#22]
We need to come up with guides. I am thinking of:

1. Contributing Guide
example:
https://github.com/rackerlabs/rackspace-how-to/blob/master/CONTRIBUTING.md

2. Style Guide
examples: 
https://github.com/rackerlabs/rackspace-how-to/blob/master/style-guidelines.md
http://help.apple.com/asg/mac/2017/
https://developers.google.com/style/

**Comment by lognaturel** [comment]
That brings up an interesting question about where different kinds of docs should live. Currently each different tool has its own contribution and style guides. They're each tailored to the particular language and context of the tool. For example, [Collect contributions](https://github.com/opendatakit/collect#contributing-code) and [Collect style](https://github.com/opendatakit/collect/blob/master/CONTRIBUTING.md#style-guidelines). It might be a good idea to pull out what is general and common and then each repo can link out to that and amend it as necessary?

**Comment by adammichaelwood** [comment]
Is @ronna saying we need contributor guides for docs or for development?

If docs -- yes, I agree. It's on my short list.

If development -- yes, I agree. But I think those should probably be in a contributing.md file on each repo, with maybe a general guide to code contributions as part of this one.

**Comment by ronna** [comment]
@adammichaelwood I am referring to contributor guides for docs, sorry I linked to developer Style guides, I did not have much time to dig and look up documentation style guides.

**Comment by ronna** [comment]
something more or less like this: https://github.com/openshift/openshift-docs/tree/master/contributing_to_docs
