### ISSUE TITLE
Make Form Design a separate section

### ISSUE THREAD

**Issue by mish24** [opendatakit/docs#225]
Currently I have added the `Form Design` documents in the same section as form building. But they have many smaller parts like guidelines, workaround and tips, etc. I wanted to get some inputs whether all this should be added on separate section in the docs. @adammichaelwood @lognaturel @yanokwa What do you think?

**Comment by adammichaelwood** [comment]
I think a single section like we have is good. I'm open to a different name is "Form Design" isn't quite clear.

**Comment by mish24** [comment]
I think Form Design should be under a different section since it's more about understanding the **anatomy of the form**, and how can we create our own forms efficiently. Although I am not sure where the line should be drawn the docs. @lognaturel Can you help?

**Comment by adammichaelwood** [comment]
I should have started the discussion of #239 in this thread, but it didn't occur to me. Since there's currently more details there, I'm closing this one and directing further discussion to #239
