### ISSUE TITLE
Add csvtable to contributor guide

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#227]
The csvtable directive is a much easier way to put tables in an rst document than the other options.
I've already used it extensively in the form-widgets page, but it isn't mentioned in the contributor guide. We should add it, as I think it would make contributor lives easier.

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by adammichaelwood** [comment]
http://docutils.sourceforge.net/docs/ref/rst/directives.html#id4

The full details don't need to be covered -- just enough to make sense. Then you can link to the full details "for more information" or something.

We should talk (here!) about whether to support/encourage the use of external csv tables.

**Comment by ankita240796** [comment]
Thanks for the reference @adammichaelwood !
