### ISSUE TITLE
Add documentation on upgrading Aggregate

### ISSUE THREAD

**Issue by ankita240796** [opendatakit/docs#228]
We should have a new doc on how to upgrade Aggregate with details of various versions. @adammichaelwood  What do you think?

**Comment by adammichaelwood** [comment]
Sure, that sounds reasonable.

 - Is there existing content to pull in on this?
 - Are there specific challenges that people are having? (Check the forum for this.)

**Comment by ankita240796** [comment]
[](https://github.com/opendatakit/opendatakit/wiki/Aggregate-Release-Notes#general-upgrade-steps)
This link has the upgrade steps and yes I checked out the forum. People have been raising issues on how to upgrade and various problems while upgrading.

**Comment by ankita240796** [comment]
[This link](https://github.com/opendatakit/opendatakit/wiki/Aggregate-Release-Notes#general-upgrade-steps) has upgrade steps and yes I checked out the forum. People have been raising issues about how to upgrade and various problems while upgrading Aggregate.

**Comment by ankita240796** [comment]
@adammichaelwood If this looks fine, I would like to work on this.

**Comment by adammichaelwood** [comment]
yes, that'd be great

**Comment by ankita240796** [comment]
@opendatakit-bot claim
