### ISSUE TITLE
Area function

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#23]
It's not well-known and I'm not finding any documentation.

https://forum.opendatakit.org/t/measureheigt-area/9128/5

@adammichaelwood I'm not really sure how to tag this one. Perhaps there should be a form design label?

**Comment by adammichaelwood** [comment]
Are there enough other functions like this that we need a function reference?
(I'm not finding anything like that...)

OR... if this is basically a one-off,
maybe we could add this to form-widgets.rst, in the location section.

**Comment by lognaturel** [comment]
This comes back to a conversation we've been having on and off about what's in specs vs. what's in docs. There are lots of very useful functions that are underused because they're basically just available at https://opendatakit.github.io/xforms-spec/#xpath-functions. Some could certainly benefit from some narrative and examples.

**Comment by adammichaelwood** [comment]
I'm adding the area() function to the geoshape widget -- it fits very naturally

As for the func reference... at the very least, it could be linked to from docs.
And docs can provide examples and then point to the full spec.
