### ISSUE TITLE
XML highlighting warning (?)

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#237]
see #206 
xml highlighting skipped-- some problem with the lexer...

**Comment by Divya063** [comment]
@adammichaelwood I guess this was due to the syntax error in the XML code

**Comment by adammichaelwood** [comment]
was it just one instance? or all of them?

**Comment by Divya063** [comment]
The first three lines of xml code were creating the problem, @ankita240796 suggested this 
> <h:html xmlns="http://www.w3.org/2002/xforms"
xmlns:h="http://www.w3.org/1999/xhtml"
xmlns:orx="http://openrosa.org/xforms/">
@Divya063 Remove the three code lines starting from line 90 and replace them with this. This will fix your error.

and this got fixed

**Comment by adammichaelwood** [comment]
awesome
