### ISSUE TITLE
Form Design Page *and Children* from old site (XForm Docs discussion)

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#239]
@mish24 has recently worked on pulling in the [Form Design Page](https://opendatakit.org/help/form-design/) -- #217 

But that page has a bunch of child pages dealing with specific XForm issues:

- Binding
- Body
- Guidelines
- Data Preloading
- Cascading Selects
- External Itemsets
- External Apps
- OpenStreetMap
- iText
- Examples
- XLSForm
- Gotchas and Workarounds

Do we think all this should be folded into docs?  
Or should it be deprecated altogether?   
Moved into the XForm specification repo?

**Comment by mish24** [comment]
we'll have XForm specific repo for documentation? The points mentioned here are important for understanding forms in general. Some of these things are important for *form breakdown*, and others for *form creation*, and there two parts make up the entire content of Form Design.

**Comment by adammichaelwood** [comment]
> we'll have XForm specific repo for documentation? 

Exists already:

https://github.com/opendatakit/xforms-spec

It's really for the specification only. In theory, usage tutorials and human-readable explanations could (should?) belong here in docs. But it's tough to delineate precisely where the line is.

**Comment by mish24** [comment]
@adammichaelwood  Exactly. It's difficult to draw a line here since everything is inter-dependent and nothing can be left out if someone is actually following these docs for understanding.

**Comment by adammichaelwood** [comment]
Will do first pass on collating/combining into something usable

**Comment by adammichaelwood** [comment]
Everything from this list either:

- has been migrated
- will not be migrated
- has another issue with more details 

I am therefore closing this issue.
