### ISSUE TITLE
Add Collect Release Notes doc

### ISSUE THREAD

**Issue by mish24** [opendatakit/docs#242]
## Description

From 1.1.7 to the latest version (Collect 1.4.12?) - just mentioning what new features were added, changes, deletions etc.

@adammichaelwood What do you think?

**Comment by adammichaelwood** [comment]
Possibly...

Do @lognaturel or @yanokwa have an opinion?

I think it could be especially cool if the notes linked to relevant info in docs, where applicable.

**Comment by mish24** [comment]
Linking to docs might be tricky but possible in some cases and not in others. Is it a good idea to include links to the issues in Collect repo for them?

**Comment by adammichaelwood** [comment]
> tricky but possible in some cases and not in others

Yeah, I'm imagining just when would be easier and relevant -- like in the release that adds a new widget, linking to the doc for that widget in form-widgets 

Linking to the issue would be helpful for some people also -- the real question is whether it would be helpful enough to be worth the effort.

**Comment by yanokwa** [comment]
To me, adding docs for a new widget doesn't add much. That is, the enumerator who is using ODK Collect is rarely the person designing the forms.

As to release notes, we have release notes on the [Play Store](https://play.google.com/store/apps/details?id=org.odk.collect.android&hl=en), on the [Forum](https://forum.opendatakit.org/t/odk-collect-v1-10/9856), and in [Github](https://github.com/opendatakit/collect/releases). I'm open to the idea of putting them in the docs, but I don't think a lot of projects do this.

**Comment by adammichaelwood** [comment]
There doesn't seem to be much enthusiasm around release notes in docs.

**Comment by yanokwa** [comment]
Agreed with this decision. Can you also file an issue to pull out the Aggregate release notes in the current docs?

**Comment by adammichaelwood** [comment]
oh, yeah - i forgot those were in there.
