### ISSUE TITLE
Image Based Forms

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#244]
Old page:
https://opendatakit.org/help/image-based-forms/

I think this page can be deprecated altogether. Thoughts?

1. Is it still true that Android has poor language support for non Latin scripts like Hindi?
   - And if it is, could we just mention using images in place of text in the Tips section?
2. Is there anything about using images that is here,that isn't clear from http://docs.opendatakit.org/form-widgets/#including-images-as-choices

**Comment by mish24** [comment]
For 1, yes it started permanently from Android 4.3 I guess. Otherwise just boxes.

**Comment by adammichaelwood** [comment]
> it started permanently from Android 4.3 

4.3 and above have good support for Hindi?

**Comment by mish24** [comment]
Yes Hindi works fine for 4.3 and above. For 2, adding media to XLSForm is included in form widgets and again in the form design doc (to be added) as well. Only new thing is "how to add localized media"

**Comment by adammichaelwood** [comment]
We cover image choices pretty well. 
We DO need a doc on localization, etc.
