### ISSUE TITLE
Verifying Downloads

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#245]
This page needs to be pulled in and edited.
I'm not sure where the best place for it is... maybe Reference?

https://opendatakit.org/help/verifying-downloaded-files/

**Comment by ankita240796** [comment]
May I work on this?

**Comment by adammichaelwood** [comment]
Sure. 
As much as possible, try actually doing the verification steps yourself.
And mention in the PR what you couldn't test. (For example, if you're not on Windows, you can't test the Windows procedure. etc.)

**Comment by ankita240796** [comment]
Sure @adammichaelwood I will do that. Thanks!

**Comment by ankita240796** [comment]
@opendatakit-bot claim
