### ISSUE TITLE
Training Guides

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#246]
https://opendatakit.org/help/training-guides/

This page has a long blog-post-like guide, which may or may not belong in the docs.
It also has a list of links to other resources, which may or may not belong in the docs.

Thoughts?

I'm not opposed to adding a Helpful Links page in Reference.
Or adding a Resources and Guides section, with this content on a page, and a page of links, and maybe some of the Tips and Workarounds stuff could end up there...

**Comment by Divya063** [comment]
@adammichaelwood I think it would be nice to have helpful links page in reference , I went through some of the links and found some of the links really helpful like Step by step for using ODK from start to finish](https://groups.google.com/forum/#!msg/opendatakit/wxXDlVl83FI/gusIaaqdYooJ) but some of the links are not available(outdated )

**Comment by adammichaelwood** [comment]
As discussed in several other places,
we are not going to curate third-party resources/tutorials in Docs.
