### ISSUE TITLE
Aggregate Usage Documentation

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#249]
The recently pulled-in doc on Aggregate Use (http://docs.opendatakit.org/aggregate-use/) is really just a handful of tips and troubleshooting points from the old site.

We need a real usage guide. This may be several pages.

This requires a bit of discussion and planning as someone takes it up.

**Comment by ankita240796** [comment]
@adammichaelwood I have updated a the usage docs and made a [PR](https://github.com/opendatakit/docs/pull/231) on that. Can you please review those changes.

**Comment by adammichaelwood** [comment]
cool! Sorry I missed that.

**Comment by adammichaelwood** [comment]
Those were good improvements, but the document itself isn't really a usage guide at the moment.

Let's start by having you iterate on that, though.

Can you pull the usage instructions up to the top and organize the information a bit? A series of unrelated bullet points is not a good doc structure.

**Comment by ankita240796** [comment]
Ya sure, @adammichaelwood I will work on that !
