### ISSUE TITLE
Briefcase "use parallel connections" feature and when it might be helpful/harmful

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#25]
opendatakit/briefcase#142

**Comment by adammichaelwood** [comment]
I sifted through the linked conversation, but I'm not sure I entirely understand.
I *think* the thing we might want to communicate is:

 - parallel connections might speed up the pull from aggregate for text-only (no media) forms (which would only really matter, I assume, if we're talking about a lot of responses)
 - it could fail in the case of media attachments

Are there any other major points to keep in mind here?

**Comment by adammichaelwood** [comment]
@lognaturel Do I have the above about right?

**Comment by lognaturel** [comment]
Users not on AppEngine should always turn the feature on and should always see a speed improvement. On AppEngine, it should speed things up always unless there are large attachments involved. If submissions have large attachments, turning on parallelism may result in timeouts and overall worse performance. In that case, it's best to experiment with both and pick what works better in practice.
