### ISSUE TITLE
Aggregate Data Transfer

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#251]
https://opendatakit.org/use/aggregate/data-transfer/

This doc needs to be edited and pulled into the current docs.
The info needs to be checked as well, as some of the third-party services may have changed their process or features.

**Comment by ankita240796** [comment]
@adammichaelwood This section can be added in the Aggregate usage guide itself. What do you think?

**Comment by SnehaniranjanaSR** [comment]
Hi I am Sneha, I am new to ODK, trying to contribute something to the forum, Can I help you with anything in this Aggregate Data Transfer? Let me know how I may help. I have a Database programming and Reporting Experience.

**Comment by ankita240796** [comment]
@adammichaelwood This issue should also be closed.

**Comment by adammichaelwood** [comment]
closed via #284 

(The auto-close thing didn't work because it doesn't recognize "Closes #x and #y")

**Comment by ankita240796** [comment]
I will take care of this in future. Thanks!
