### ISSUE TITLE
Validate 

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#254]
https://opendatakit.org/use/validate/

This page needs to be checked, edited, and pulled in.
The person doing this should actually install and use the tool.

Also, the existing page is poorly organized (it includes usage instruction under the heading "Installation"), so it could stand a little re-writing for clarity.

This will be a new doc in the Form Builder TOC.

**Comment by nadaa** [comment]
I will work on this @adammichaelwood.

**Comment by nadaa** [comment]
@opendatakit-bot  claim

**Comment by nadaa** [comment]
@opendatakit-bot label  "in progress"

**Comment by ankita240796** [comment]
@adammichaelwood This issue has to be closed.

**Comment by adammichaelwood** [comment]
closed via #266
