### ISSUE TITLE
Document Aggregate limitations 

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#26]
Some good ones on this issue - https://github.com/opendatakit/briefcase/pull/142#issuecomment-315474501 and I'm sure there are more on the dev wiki

**Comment by ankita240796** [comment]
May I work on this?

**Comment by ankita240796** [comment]
May I work on this ?

**Comment by troublemagnet** [comment]
@opendatakit-bot claim

**Comment by adammichaelwood** [comment]
@troublemagnet: 
@ankita240796 already asked to work on this. I should have responded earlier.

**Comment by troublemagnet** [comment]
@adammichaelwood Sure sir I'll work on other issues.

**Comment by ankita240796** [comment]
Thanks @adammichaelwood !
