### ISSUE TITLE
Document how to use Briefcase to pull forms directly from device

### ISSUE THREAD

**Issue by ronna** [opendatakit/docs#27]
How to pull forms directly from the device and its limitations not documented:
https://forum.opendatakit.org/t/export-data-from-mobile/9126

**Comment by troublemagnet** [comment]
I'd like to work on it.

**Comment by adammichaelwood** [comment]
this would need to be part of a larger doc on Briefcase

**Comment by troublemagnet** [comment]
@adammichaelwood  sir this has been already been documented.
