### ISSUE TITLE
Limitations of time widget

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#283]
The time widget doesn't work well across daylight savings time boundaries because it does account for timezones but doesn't know what day the time was saved. For example, if a time is saved in summer time and then the form is opened in winter time, the time be shown as off by an hour. However, the underlying value will be correct.

See opendatakit/collect#170 for more details

**Comment by ankita240796** [comment]
@lognaturel Do we need a separate doc for these limitations? May I work on it?

**Comment by adammichaelwood** [comment]
@lognaturel I wonder if this should be an entry in some new "Known Issues" document.

**Comment by lognaturel** [comment]
I would tend to put it with the description of the time widget since that seems it's where someone will be most likely to get value out of it.

Maybe we leave it open until it's clearer where it should go?

**Comment by adammichaelwood** [comment]
I'm also curious under what circumstance you would want to know a time, and not the date that goes with it. Because if you only want to know a time in the abstract ("Lunchtime is always at 12:30"), it seems like that would be free of timezone context.

**Comment by lognaturel** [comment]
You can see from the thread on Collect that we really struggled with this issue and how to address it without breaking existing forms. I really don't know why timezone is included in the time-only widget and I'm not sure whether anyone relies on it. That said, I don't think it would be wise to change the backing data type (by removing TZ or adding date). Perhaps we could add a `timeWithoutTZ` type at some point.

**Comment by adammichaelwood** [comment]
> Perhaps we could add a timeWithoutTZ type at some point.

That would be sensible. "Abstract Time"
