### ISSUE TITLE
Visualizing Data with Google Fusion Tables, Google Earth

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#288]
[This doc](https://www.google.com/earth/outreach/learn/visualize-field-data-in-google-earth-and-fusion-tables/) has some interesting info that would be cool to have in our Docs.

That doc is not well organized or well written, though, so rather than get permission and fold it in, the procedures should be followed and a new doc written. (Also check the forum and other sources to see how other people are using these features.)

-----

Discussion question:

This isn't *directly* about using ODK -- but about using Google products to visualize data coming out of ODK. So it may not belong in the Docs? Not sure. Worth talking about.

**Comment by Divya063** [comment]
@adammichaelwood Can I take this?

**Comment by adammichaelwood** [comment]
Sure.

**Comment by Divya063** [comment]
@opendatakit-bot  claim
