### ISSUE TITLE
Setup CircleCI to publish to S3

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#29]
- [x] Commit from @adammichaelwood with command to build locally
- [x] Add circle.yml file to build master and pull requests
- [x] Add badge to readme.md to indicate build status
- [x] Add reporting to Slack #docs-pulse for failed builds
- [x] Setup S3 bucket to hold docs
- [x] Setup DNS, Cloudfront for https://docs.opendatakit.org
- [x] Add keys to CircleCI to automatically upload docs to bucket
- [x] Setup SSL for https://docs.opendatakit.org
- [x] Add command to upload builds to S3
- [ ] Verify builds trigger CloudFront updates

**Comment by yanokwa** [comment]
@adammichaelwood Whenever you are ready, please update the issue with the command I can use to build the docs and spit out HTML into a folder. Once I have that, I'll be able to implement it in CircleCI.

**Comment by adammichaelwood** [comment]
More detail will be in the Contributor Guide, but for now:

 - use python 3
 - once: `pip install -r requirements.txt`
 - build: `sphinx-build -b html [path/to/repo] [path/to/output]

 (so, I do: `sphinx-build-b html . build`  -- and `/build/` dir is gitignored

Note: the `-b` flag specifies the builder, which  is `html` for a website

**Comment by adammichaelwood** [comment]
(Note, for anyone else reading this... if you are running the build command in a local machine or otherwise anywhere outside of an ad hoc container... you should probably use a python virtual environment. There will be details about this in the Contributor Guide, in the docs.)

**Comment by yanokwa** [comment]
Alrightly, so the CI server now builds on every commit and per-commit builds can be found on CircleCI at https://circleci.com. Login with your GitHub account, click the commit you'd like to see, then find the build folder with the HTML in the Artifacts tab.

**Comment by yanokwa** [comment]
@adammichaelwood Merges to master now build immediately to a static site on S3 (http://docs.opendatakit.org.s3-website-us-west-2.amazonaws.com) and eventually that build makes it to a Cloudfront (CDN) that https://docs.opendatakit.org is pointed to.

**Comment by yanokwa** [comment]
Closed by #45.
