### ISSUE TITLE
Contradiction about images storage in ODK Collect's documentation

### ISSUE THREAD

**Issue by Ghanisen** [opendatakit/docs#296]
## Description

In http://docs.opendatakit.org/collect-forms/, it is mentioned 

> Media files should be placed in a **folder** labelled form-name-media.

However, in http://docs.opendatakit.org/form-widgets/#image-options it is mentioned: 

> The media files must be uploaded to the Android device in the /sdcard/odk/forms/ directory, in a **file** labeled form-name-files. It should be a **folder**.

**Comment by adammichaelwood** [comment]
Please issue a PR to correct.

Also, can you look into whether the folder should be labeled `*-files` or `*-media`.
