### ISSUE TITLE
Track inactive claimed issues (ODK bot) 

### ISSUE THREAD

**Issue by Divya063** [opendatakit/docs#298]
Feature:
If a claimed issue has not been updated for a week, @opendatakit-bot  should post a comment on the inactive issue to ask the assignee if they are still working on the issue.Assignee should reply to the comment to  notify the bot that he/she is still working on it.If the bot  does not receive a response from the assignee within certain number of days it should automatically remove the issue's current assignee(s) and the "in progress" label to allow others to work on an inactive issue.

**Comment by troublemagnet** [comment]
I totally agree with @Divya063. Most of the issues have been inactive for more than a week.

**Comment by yanokwa** [comment]
According to https://github.com/opendatakit/zulipbot/blob/master/src/config.js#L34 the bot should remind claimers after 7 days if they haven't worked on an issue. And then if there is no action on the issue, it removes the claim 3 days later (so a total of 10 days to work on an issue).

Is there a claimed issue where this process has failed?

**Comment by Divya063** [comment]
yes, here are some of the issues:
https://github.com/opendatakit/docs/issues/97
https://github.com/opendatakit/docs/issues/3
https://github.com/opendatakit/docs/issues/288

**Comment by ankita240796** [comment]
@Divya063 @yanokwa There is same problem with some inactive PRs too where changes have been requested but not still made. I am working on issue #97 but it requires a form design doc where the new section will be added. PR #217 for form design doc is inactive. Same is the case with PR #222 .

**Comment by yanokwa** [comment]
Well, we've filed the issue upstream, so that's all we can do at this time. We can't trust the bot to do everything 😂.

I propose we close this issue, and as a stop-gap, @adammichaelwood (on this repo) and @lognaturel (on the other repos) occasionally sweep the issues to find stale issues.

@adammichaelwood, if you agree, please close this issue.

**Comment by adammichaelwood** [comment]
I agree.

**Comment by yanokwa** [comment]
Fixed by https://github.com/opendatakit/zulipbot/commit/6ae9dbd043c2c0934f1005d0a152c4b4230dca9b
