### ISSUE TITLE
Using offline map tiles

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#3]
This isn't currently documented anywhere. 

opendatakit/opendatakit#1260 is the original issue filed by @florianm and includes a link to a basic description [here](https://github.com/opendatakit/collect/pull/1045#issuecomment-305356422).

**Comment by Divya063** [comment]
@lognaturel I would like to work on this

**Comment by lognaturel** [comment]
@pari0770 expressed some interest in it. @pari0770 did you want to explore this one?

One additional thing to document is that PBF tiles are not supported -- https://github.com/opendatakit/collect/issues/1093#issuecomment-306382003

**Comment by pari0770** [comment]
@lognaturel yes, I am exploring this

**Comment by adammichaelwood** [comment]
@pari0770 Please claim the issue if you are working on it.

**Comment by pari0770** [comment]
@opendatakit-bot claim

**Comment by Divya063** [comment]
@pari0770 Are you still working on this?

**Comment by lognaturel** [comment]
More details at https://forum.opendatakit.org/t/role-of-the-layers-folder-in-odk-collect/10168/6?u=ln

**Comment by Divya063** [comment]
@opendatakit-bot claim
