### ISSUE TITLE
Code samples require side scrolling

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#305]
If a line in a code sample is too long, you have to scroll sideways.

I don't think this is ideal... but maybe it it (?).

At any rate, I think the fix is just some CSS to wrap overflow lines in code blocks.

If someone could do it, and submit a PR -- at least we could see if it is an improvement.
(It might not be.)

Note: I can imagine it being the case that some languages wrap better than others. For example, `rst` blocks will probably read much better when wrapped, but XML might not. Looking into how css classes are applied based on language, and making it something we could choose on a per-language basis would be extra cool.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
