### ISSUE TITLE
Projecting ODK Collect onto another screen

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#306]
For users who need to train others on how to use ODK Collect, it would be very nice to have instructions on how to project ODK Collect on a screen.

According to https://forum.opendatakit.org/t/showing-odk-collect-form-with-projector/10063, a number of people use and like Vysor, so we should link to that and provide high-level instructions. It's great for users who have an Android device and USB debugging turned on. The upside is that it's easy to get started. The downside seems to be ads every 30 minutes (or paying $40 for it, which is a fair price!)

For more advanced users, we should point to instructions on how to install the Android emulator and get ODK Collect installed. The upside of the emulator is that it's free, you don't need a device, and you can install different versions of Android. The downside is that it's a bit big and slow and a pain to install. We want to reduce the pain of that install and unless there is a great reason, we don't want to have people use Android Studio.

I'm imaging that this document would be part of some deployment tips guide.

Oh, and whomever takes on this issue needs to *actually use Vysor* and *actually use the emulator* and make sure it all works nicely, preferably on Windows.

**Comment by Divya063** [comment]
@yanokwa I would like to take this issue

**Comment by Divya063** [comment]
@yanokwa The custom android emulator is really slow, that's why I use genymotion , It is free for personal use, but it is a commercial product,

**Comment by yanokwa** [comment]
I do think Genymotion is lighter and easier, but the license is clear that you can't use it if it `might materially benefit Licensee’s or any third party’s professional purposes`. For example, if someone is working as a volunteer for a non-profit, they probably can't use it without violating the license because then non-profit has a professional purpose. Bottom line, I want to be respectful of the license when we write docs.

I'm OK mentioning that people can use Genymotion, but I think we should document a tool that works for everyone (the Android emulator, Vysor, maybe something else). And to your point, it might be good for us to mention that the emulator can be slow and that Genymotion is likely faster (but only for personal use) and let people make that choice.

Before this is assigned, I think @adammichaelwood should think about where this will likely go in the docs.

**Comment by adammichaelwood** [comment]
> I think @adammichaelwood should think about where this will likely go in the docs.

In the Collect TOC, I imagine.

**Comment by Divya063** [comment]
@opendatakit-bot  claim

**Comment by adammichaelwood** [comment]
Just to expand on @yanokwa point above...

if genymotion is a lot easier, then all we need to do is mention that it exists. People will come to their own conclusions and won't need a doc from us explaining how to use it.

But the android studio is the canonical solution, so we should do our best to help people out with that. At the same time, we don't need to re-create their documentation.

**Comment by Divya063** [comment]
@yanokwa @adammichaelwood Vysor is working perfect but using android emulator without installing android studio is quite cumbersome process. Command line can be used to create and run the emulator but as [android](https://developer.android.com/studio/tools/help/android.html) command is no longer supported, `sdkmanager` command has to be used to install packages from the command line. There are few problems with `sdkmanager`:
1.  It is not user-friendly  as there is no GUI interface.
2.  Copy-pasting packages names and running ` sdkmanager` takes too much time.Even with --verbose, this command doesn't give any information that it is computing something and then it creates confusion among the users if the command is still running or not.

Officially GUI is not supported but I found some[ links](https://stackoverflow.com/questions/41407396/is-gui-for-android-sdk-manager-gone#answer-45940959) through which previous versions of android sdk tools can be downloaded and they are working fine.

**Comment by adammichaelwood** [comment]
I think it is okay to provide Studio and non-Studio instructions emulator, and mention what the advantages/disadvantages are. You would need to make clear what has been deprecated or lacks support, etc.

This is is also something that can be added to the docs in stages. So you don't have to cover every possible approach in one PR.

**Comment by yanokwa** [comment]
@Divya063 Thanks for looking into this! I now remember that Google has made the Android emulator even harder to install. What a shame.

I'd propose that we list Vysor, Genymotion, Android Studio and then put a few sentences about the various tradeoffs. I'd leave off the non-Studio emulator because it is deprecated and there are suitable alternatives. If there ends up being more demand for that, maybe we can add that latter.
