### ISSUE TITLE
Going quickly from XLSForm to a form on a device

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#307]
When doing a form design session, I usually have Excel and an emulator going at the same time. I design the forms in Excel, then use pyxform to convert it to XML, then use adb to push the form to an emulator using the command line (e.g., `xls2xform form.xlsx form.xml && adb push form.xml /sdcard/odk/forms/`).

The process is relatively straightforward, but it seems magical if you don't know the individual steps. The docs have these individual pieces already (e.g. how to install pyxform, how to use adb), but it'd be nice to tie them together with a little bit of prose that we can point people to.

This is important because the alternatives (e.g., convert using XLSForm online, then upload to Aggregate, then download to device) requires a connection, which many do not have. Also, it's slow and no one like slow.

**Comment by troublemagnet** [comment]
I'd like to work on this.

**Comment by adammichaelwood** [comment]
@troublemagnet I think that would be great.

The "bit of prose" might cover:

 - the purpose of this is for iterating on a form design in excel and seeing the changes on your device as you work
 - using these command line tools is way faster than what someone might try doing:
     - save the spreadsheet
     - upload it to the online xlsform onverter
     - upload the output to Aggregate
     - fetch form from server in Collect

This could be a section in a new doc titled `Form Design Tips` -- I'm sure we'll have others as time goes along.
