### ISSUE TITLE
ODK Collect and Comment feature

### ISSUE THREAD

**Issue by fabla** [opendatakit/docs#313]

**Comment by lognaturel** [comment]
Hi @fabla! This repository is for ODK documentation. Issues should be filed to keep track of information about ODK that needs to be added to the documentation.

I see that in the issue comment you have left the following message:
> I am suggesting if there could be a comment feature in collect which could allow users to leave any vital comment on any questions that they think it is important to the study. and sold if xlsform offline can be update to convert the comment type in the xlsfom to xform which can work on collect.

This looks like either a support question or a feature request. Feature requests should go to https://forum.opendatakit.org/c/features and make sure to include as much detail as you can including how the user would interact with the feature, how the data from the feature would be used, etc.
