### ISSUE TITLE
Deal with color profile problem locally before PR

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#330]
We recently had a problem (#323) caused by an image having color profile that was incompatible with with [pngquant](https://pngquant.org/) (a lossy image compression tool we use on deployment).

There was no way for the contributor to know that this would be a problem. It appears that *some* Android devices use the problematic color profile. (Who knows which ones?) 

The solution -- which is easy -- is for screenshots with the bad color profile to be converted.

But if you don't run pngquant locally, there's no way to know this is going to happen. (Unless it has happened to you.)

## Possible solutions

 1. require contributors to install `pngquant` and add it to `b.sh` to catch errors
 2. add [pillow](https://python-pillow.org/) to `requirements.txt` and include color profile checking/conversion in `ss.py` (along with instructions for running it independently)
 3. add color profile conversion via pillow to circleCI and not make contributors think about it

I think I like the second option. I'm also good with combining 1 and 2.

The last option is definitely an option, but I think is probably the least good one.

Doing nothing is also an option, and should not be overlooked.

**Comment by troublemagnet** [comment]
I don't think *doing nothing* is a good option. It's always better to avoid failed builds. The bad png fail is not at all intuitive as there's no warning that is generated by the sphinx build locally. And when the possible solutions are really easy to be incorporated, we might just do it. I think the minimum we should is to adopt the first solution. However even I feel that combining 1st and 2nd would the best.

**Comment by adammichaelwood** [comment]
@troublemagnet If you want to look into this:

> add pillow to requirements.txt and include color profile checking/conversion in ss.py (along with instructions for running it independently)

you could. It would be helpful and probably doable in reasonable time.

**Comment by troublemagnet** [comment]
@adammichaelwood yes sir, I'll do it.
