### ISSUE TITLE
Update behavior of form metadata username

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#339]
In versions prior to Collect 1.11.0, the form metadata username was always used as the preload value. Now the server username is used if no form metadata username is set.

https://github.com/opendatakit/collect/issues/1306

**Comment by Divya063** [comment]
@lognaturel  May I work on this?

**Comment by lognaturel** [comment]
@Divya063 Sounds good to me!

**Comment by Divya063** [comment]
@opendatakit-bot claim
