### ISSUE TITLE
Global rst link refs for common links (docs repo, file an issue, the forum, the slack)

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#346]
Pretty sure this would go in `rst_epilog` in `conf.py`.
I think it should just be the link targets, not a full substitution text, so we can quickly do:

```
If you find a problem, `file an issue <docs-issues>`_ 

Be sure to `read the contributors guide <docs-contributor-guide>`_

You can ask about that in the `ODK Slack <odk-slack>`_

etc...
```

--

This would also need a short section in the contrib docs.

**Comment by Divya063** [comment]
@opendatakit-bot claim
