### ISSUE TITLE
Seperate docs folder for each ODK tool

### ISSUE THREAD

**Issue by ronna** [opendatakit/docs#35]
@adammichaelwood I propose that we have a folder for each ODK tool/component and keep the docs for the specific tool in that folder. Most if not all tools might have the same structure and it will be very difficult to name the files with the current setup. For example we already have a  getting-started.rst (for Collect), we can not have another getting-started.rst say for ODK build or ODK Aggregate with the current set up.

**Comment by troublemagnet** [comment]
@adammichaelwood sir may I work on organizing the directory structure?

**Comment by adammichaelwood** [comment]
No. 

 This is not work that actually needs to be done. It is not typical to organize sphinx repository as suggested above.  I know that having every document in the root seem a little disorganized, but it provides greater flexibility for organizing and rearranging the tables of contents as The best or most useful arrangement becomes clear.
