### ISSUE TITLE
Standardize language and document in contributor guide

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#351]
Within http://docs.opendatakit.org/collect-settings/ we have "allows you to list..." and "allows us to list..." and "lists...". It would help with coherence to pick one and stick with it. I prefer the last form which is more direct and formal.

**Comment by jaredbhatti** [comment]
@lognaturel  I think is fixed. Can you verify? If there's additional work, feel free to comment.

**Comment by yanokwa** [comment]
Agreed.
