### ISSUE TITLE
Fix style of guilabel in TOCs

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#362]
If a title has a `guilabel` text role, the style is retained in the TOC, which looks weird.
![screen shot 2017-11-24 at 3 24 10 pm](https://user-images.githubusercontent.com/1776241/33225404-aa761232-d12b-11e7-85b4-44d401143e5a.png)

(Maybe it doesn't look weird? This issue needs a second opinion.)

**Comment by ankita240796** [comment]
It actually does look weird, the style should not be retained in the TOC.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
