### ISSUE TITLE
Document new Collect calendar types

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#378]
The upcoming release (v1.12 to be released ~12/17) adds `coptic` and `islamic` appearances for the calendar.

**Comment by Divya063** [comment]
@opendatakit-bot claim

**Comment by Divya063** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [PR for issue #378](https://trello.com/c/pcvD49rv/4-pr-for-issue-378)
