### ISSUE TITLE
Document range widget

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#38]
What it looks like in Collect, the different appearances, how to generate one in Build or XLSForm.

https://github.com/opendatakit/collect/issues/105

**Comment by adammichaelwood** [comment]
The relevant widgets needs to be added to the all-widgets form.

**Comment by Divya063** [comment]
@adammichaelwood Can I work on this?

**Comment by lognaturel** [comment]
Now that this is usable from XLSForm I think it should be prioritized.
