### ISSUE TITLE
Describe all intents

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#4]
@rishsethia put together some docs about using Collect's [Intents](https://developer.android.com/guide/components/intents-filters.html) at opendatakit/collect#74 that need a place to be!

**Comment by smartyrad** [comment]
@lognaturel @adammichaelwood  Shall we include the documentation prepared in opendatakit/collect#74 under a new sub section called "Intents" in the Collect section of our documentation i.e. below https://docs.opendatakit.org/collect-forms/# ?

**Comment by adammichaelwood** [comment]
This is really part of building a doc on form design, not using Collect.

**Comment by smartyrad** [comment]
Okay sure, I'll work on it  :)

**Comment by adammichaelwood** [comment]
@lognaturel  I was confused about this.

The content here is developer docs, not user/implementer docs. Do you we think it really belong here? Or....?

**Comment by lognaturel** [comment]
I think there should be a section on building on top of or integrating with ODK Collect. This is information for developers, yes, but not for Collect developers. It's for developers of other apps that integrate with Collect. Does that make sense?

To make this idea more concrete, check out the intent tester app [here](https://github.com/grzesiek2010/collectTester). This will eventually be moved to the Open Data Kit organization once it's finalized and should probably be linked to from the documentation.

Another example of integrating with Collect is through external apps that fetch data such as https://github.com/opendatakit/counter

**Comment by adammichaelwood** [comment]
> this is information for developers, yes, but not for Collect developers. It's for developers of other apps that integrate with Collect. Does that make sense?

I see, yes -- that makes sense. 

(I had originally thought this was for form designers trying to use intents to launch other apps.)

@smartyrad 

Can you add some text at the top of your doc that explains what the doc is for. You describe what an intent is, but it isn't clear (unless you already know) that the purpose of the doc is to show people how to launch ODK Collect and have it open at various specific points in the app.

You can also add a new TOC tree directive in `index.rst`, with the title `Developing with ODK`. This doc will live there, and we'll start adding other content to that section as we come to it.

**Comment by troublemagnet** [comment]
@opendatakit-bot  claim

**Comment by ankita240796** [comment]
@troublemagnet I have already prepared a doc on this and was about to issue a PR. I am really sorry for interrupting you as I forgot to claim the issue. Can you please work with some other issue.

**Comment by troublemagnet** [comment]
I started too but nevermind.

**Comment by ankita240796** [comment]
I am really sorry about this. If you want to work this, I will not issue the PR.

**Comment by troublemagnet** [comment]
It's fine if you already prepared a doc. I just spent time in understanding the issue and researching.

**Comment by ankita240796** [comment]
Thank you so much @troublemagnet. Please review my PR, it will help me in making the doc better.

**Comment by lognaturel** [comment]
Thanks for the good collaboration @troublemagnet, @ankita240796.
