### ISSUE TITLE
Clean up repo

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#401]
At very least, drop all the content into a [source directory](http://www.sphinx-doc.org/en/stable/glossary.html#term-source-directory).

This would mean also updating build scripts, etc.

I still [don't think it's a good idea to subdivide pages into a series of folders](https://github.com/opendatakit/docs/issues/35), as that needlessly complicates page organization. However, moving all the source files out of the top level would separate them from all the other things: build config files, utility scripts, settings, etc.

**Comment by adammichaelwood** [comment]
From Slack:

> Hi all. I've started work on https://github.com/opendatakit/docs/issues/401 .
>
> I moved all the rst files into a src directory and fixed all the image paths to be absolute. This works, but the problem is that Sphinx reflects the directory structure in the path. So http://docs.opendatakit.org/collect-intro becomes http://docs.opendatakit.org/src/collect-intro.
>
> I am having trouble finding a way in restructuredText to control paths. Does anyone have any documentation they can point me at to help with this problem?

My understanding is that if you put `conf.py` in the `src` directory, and update the build script to specify it as the source directory, sphinx-build treats that as the document root. (See the [sphinx-build docs](http://www.sphinx-doc.org/en/stable/man/sphinx-build.html)...)

(There's also [something about putting `conf.py` in it's own directory](http://www.sphinx-doc.org/en/stable/glossary.html#term-configuration-directory), but I don't understand the point of that.

I am unclear whether `img`, `vid` or `static` need to be under `src` in this case. (I think they do.)

Ideally, we'd have a `src` dir that is everything content related, a `util` dir that has all our custom scripts and utilities.

**Comment by adammichaelwood** [comment]
To clarify, I *think* that if once you move everything to `src`, then:

```
sphinx-build -b dirhtml . build
```

will need to be changed to 

```
sphinx-build -b dirhtml src build
```

and then everything will work as it is supposed to.

That will need to be updated in the build utility (`b.sh`), the documentation, and the CircleCI config.

**Comment by jbeorse** [comment]
Ah, thanks for the update. This does work and I had gathered as much about the build command change. I had forgotten the CircleCI config though. I will update that and issue a pull request.

**Comment by jbeorse** [comment]
Actually, I have only moved source files into the `src` directory and done nothing to move custom scripts and utilities into `util`. Which files would need to be moved? `video.py`? 'style-test.py`?

**Comment by ankita240796** [comment]
Some updates will be needed to the code-structure of ``style-test.py`` as well because it searches for files in docs repo. We will need to the update the code so that it searches for files in ``src`` directory in the docs repo.

**Comment by adammichaelwood** [comment]
Most of what I wanted to happen here happened with the odk-2 repo reorg. 
If anything else seems important over time, we should open more specific issues to deal with them.
