### ISSUE TITLE
Organize CSS, document better CSS comments

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#410]
The CSS is turning into a hot mess.

We need to:
 - organize what is there into reasonable sections of related things
 - comment it so that we know what things are before we forget 
 - write some rules for the contrib guide about how to add new CSS in a way that is sensible (comments, maybe a mention of the PR or issue being addressed.)

**Comment by ankita240796** [comment]
@opendatakit-bot claim
