### ISSUE TITLE
Bug: Broken link on Collect page

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/docs#414]
## Description

The Collect page at https://opendatakit.org/use/collect/ notes that the page is deprecated and suggests that the user visit http://docs.opendatakit.org/collect-guide/. However, that URL gives a 404 error.

Let me know if this is the wrong repository for this issue... Apologies if it's not!

**Comment by adammichaelwood** [comment]
@yanokwa 
The relevant redirect is in place at `s3_website.yml`  
however... it seems to make a distinction between:  
`collect-guide` 
and
`collect-guide/`

Is there a way to make both work?

**Comment by adammichaelwood** [comment]
> Let me know if this is the wrong repository for this issue... Apologies if it's not!
@matthew-white This is the appropriate place. Thanks for the heads up.

**Comment by lognaturel** [comment]
Thanks for reporting, @matthew-white. I fixed that one.

@adammichaelwood Have you tried changing the redirect to end with /? when I look at other Sphinx docs it looks like most of them serve documents that end in .html (e.g. http://www.sphinx-doc.org/en/stable/invocation.html or http://mode.readthedocs.io/en/latest/faq.html). Why don't the odk docs work that way? The urls ending in / do seem odd.

**Comment by adammichaelwood** [comment]
I don't believe URLs should include file extensions.
cf. "What to leave out" in this: https://www.w3.org/Provider/Style/URI

I think the slash-ending is weird, but browsers and web servers don't care: `http://example.com/this` and `http://example.com/this/` are the same resource. The problem here has something to do with how the redirect works -- it is only searching for the exact match (with or without the slash, as the case may be).

**Comment by lognaturel** [comment]
Good reference, I'm sold on the no-extension approach.

**Comment by yanokwa** [comment]
And just so we don't forget, @adammichaelwood, when you make the change in s3_website.yml, please also include the slash and noslash in the redirects note at https://github.com/opendatakit/docs/blob/master/contributing.rst.

**Comment by lognaturel** [comment]
What is the status here? @yanokwa were you going to look into whether both the variants with and without slashes could automatically be supported? Or did you decide both would need to be added manually?
