### ISSUE TITLE
Add info on changing form language and saving a form while filling it

### ISSUE THREAD

**Issue by ankita240796** [opendatakit/docs#417]
There is no information on changing language of a form if it is available in multiple languages as well as saving a form while you are filling it. This needs to be added to ``collect-filling-forms.rst``.

**Comment by adammichaelwood** [comment]
normally you should have filed this as two separate issues with two separate PRs.

(Don't worry about it on this one, since you already filed a good PR on it.)

**Comment by ankita240796** [comment]
I will take care of this in future. Thank you!
