### ISSUE TITLE
Redirects not working for sub-sections in a page

### ISSUE THREAD

**Issue by ankita240796** [opendatakit/docs#425]
When we rename a page and add a redirect, the redirect is not added for the sub-sections in the page. For example, if the page collect-guide is changed to collect-intro, https://docs.opendatakit.org/collect-guide is successfully redirected to https://docs.opendatakit.org/collect-intro/ but https://docs.opendatakit.org/collect-guide/#learn-more-about-odk-collect is not redirected.

![screenshot from 2018-01-04 16-36-50](https://user-images.githubusercontent.com/15226041/34560840-8fa354e4-f16d-11e7-8859-57543e6c8cbe.png)

**Comment by lognaturel** [comment]
Note that https://docs.opendatakit.org/collect-guide#learn-more-about-odk-collect works as expected so this is an extension of the trailing-slash-not-redirecting problem.
