### ISSUE TITLE
Build and maintain inventory of migrated content

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#436]
A lot of content has been moved over from the ODK website, [developer wiki](https://github.com/opendatakit/opendatakit/wiki) and other sources into the docs here. It's hard to tell which content should be considered the "source of truth."

I have started a document at https://docs.google.com/spreadsheets/d/1IfZydsmSWvxEzBE5yO7-2FZVJt6UY4dDGc4GzCjlnmc/edit#gid=0 to keep track of the migration status. Each resource from the website and wiki should eventually be listed there. It might be useful to use some kind of crawler or site mapper to generate the initial list of resources and then search can be used on the docs site to find the corresponding pages. I have given write access to @adammichaelwood @yanokwa @ankita240796 @Divya063. Everyone has commenting access and I can add more people if interested.

This will help make sure that all redirects are properly addressed in the [website migration](https://forum.opendatakit.org/c/contributions/website) and reduce confusion caused by duplicate content.

**Comment by adammichaelwood** [comment]
I've added a couple sheets to the document. The original shee tnow has a list of all the old-site pgaes that are specifically relevant to ODK [1.0]. There's now also a sheet for blog posts (which might contain some useful content) and the ODK 2.0 pages (which I figured might be useful for other ppl). I'm sifting through them as I walk through on an editing pass through the whole doc repo.

**Comment by adammichaelwood** [comment]
The main sheet (**ODK Pages**) has been completely updated with the current status of everything from the old site that is directly related to ODK.

Along with that, the pages that have been migrated have all been updated on the old site with a deprecation notice and grayed out text. Barring some reason I don't know about, it seems like those pages (marked TODO: Redirect) could all be `301`ed immediately.

Several pages are marked TODO:?  -- @ln and/or @yanokwa can probably provide some guidance here. This is mostly content that is in-theory appropriate to docs, but might no longer be relevant. (PLus a few other random things.)

A whole section of pages are related to editing XForm XML directly. There is already a conversation about those pages in issue #239.

I'll add the wiki pages next and we can sift through that. Is the plan to completely deprecate the github wiki?

**Comment by adammichaelwood** [comment]
I believe all of this content that is doc-related has been accounted for,
either moved over or at least issues made of them, with the text copied in.

IT would be good to get additional review, though,
before the old site disappears.

What I'm most concerned about before the new site launches is redirects.
The new site (or it's server, whatever) needs to catch all these existing URLs and redirect --- mostly to the docs. Is that happening? Can I help in some way with that? I don't mind sitting an adding entries to a config file or whatever.

**Comment by adammichaelwood** [comment]
I have made a final review over the spreadsheet now that the new site and its redirects have all mostly settled. 

There are just a few URLs that might be better off redirected some place else, and I have opened issues for those:

https://github.com/opendatakit/website/issues/165
https://github.com/opendatakit/website/issues/166
https://github.com/opendatakit/website/issues/167
https://github.com/opendatakit/website/issues/168

Therefore I am calling this issue.... CLOSED.
