### ISSUE TITLE
Add osm question, link to Open Map Kit, in question types

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#445]
From old docs:
https://opendatakit.org/help/form-design/open-street-map/

@ln Is there any connection between this and #3 ?

**Comment by lognaturel** [comment]
No relationship. 

I'm not sure ODK documentation needs a specific section about Open Map Kit. I think linking to http://www.openmapkit.org/ from the question type is sufficient.

**Comment by adammichaelwood** [comment]
>  linking to http://www.openmapkit.org/ from the question type is sufficient.

We don't currently have documentation for the `osm` question in Question Types.
Would it just make sense to have a section, say very little, and link to the open map kit docs?
