### ISSUE TITLE
Triage through proselint checks to prepare a list of excluded checks

### ISSUE THREAD

**Issue by ankita240796** [opendatakit/docs#467]
In reference to #94, #427.
Proselint checks: https://github.com/amperser/proselint/tree/master/proselint/checks

**Comment by ankita240796** [comment]
@adammichaelwood We can mention the proselint checks to exclude here as well.

**Comment by ankita240796** [comment]
Exclude the check: https://github.com/amperser/proselint/blob/master/proselint/checks/misc/but.py
Prepare a custom check for this.

**Comment by ankita240796** [comment]
Exclude: https://github.com/amperser/proselint/blob/master/proselint/checks/consistency/spelling.py as we already have a check for us vs uk spelling. Add any extra spelling found to the us vs uk check.

**Comment by ankita240796** [comment]
@adammichaelwood  I have gone through the checks in proselint. There is no such check which will create an issue with semantic line breaks. So, we can safely proceed with it. 
Further, there are three checks which are just commented out and there is no code as in this one:
https://github.com/amperser/proselint/blob/master/proselint/checks/misc/usage.py
But I think we can keep them on as in case of any update to these checks we may need to use them.

**Comment by adammichaelwood** [comment]
This work has been completed.
