### ISSUE TITLE
Downloadable files

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#47]
Where (and whether) to put them in the docs.
And then document how to link to them.

**Comment by ankita240796** [comment]
@adammichaelwood I think we should put the downloadable files in the doc itself instead of giving links to old docs. We can place them in a new folder _downloads_ and then link them by using <code> :download:`file </path/to/file>` </code>

**Comment by adammichaelwood** [comment]
This is becoming relevant, and we need a way to provide downloadable files and documents.

Should not be hard:

 - We need a new directory in the source. Probably `/files/` or `/downloads/` though someone should look into Sphinx docs to make sure that isn't reserved for some other use. (Or if there is a standard name for this dir other than `/files/`)
 - The `conf.py` has to be updated so that the directory is copied over on build.
 - Docs need to be updated to show where to put downloadable files and how to use the [`:download:`](http://www.sphinx-doc.org/en/stable/markup/inline.html#role-download) role.
 -

**Comment by ankita240796** [comment]
@adammichaelwood May I work on this?

**Comment by adammichaelwood** [comment]
That would be great.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
