### ISSUE TITLE
Install JAVA 8 procedure error

### ISSUE THREAD

**Issue by aurdipas** [opendatakit/docs#484]
aggregate-tomcat.rst

in the installation procedure for java8 in Linux there's an error on the set the JAVA_HOME variable.
It explain first how to install Java 8  but the JAVA_HOME is set to java7

"Now open /.bashrc with your editor and add export JAVA_HOME = /usr/lib/jvm/java-7-openjdk-amd64 at the bottom of that file. "

![2018-02-02 10_28_26-installing on tomcat local or cloud open data kit docs](https://user-images.githubusercontent.com/5656097/35726313-c6098988-0804-11e8-80fd-2f80fe699777.png)

**Comment by akshay-ap** [comment]
@opendatakit-bot claim
