### ISSUE TITLE
image-map appearance for select and select multiple

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#490]
Will be available in Collect 1.13+. See code and sample forms at https://github.com/opendatakit/collect/pull/1807

**Comment by adammichaelwood** [comment]
There was a mention in slack about someone putting together a nice example for this. Is that available?

**Comment by lognaturel** [comment]
@grzesiek2010 has a great one at https://github.com/opendatakit/sample-forms/blob/master/body.xml (there's also a body-media folder)

**Comment by adammichaelwood** [comment]
my assumptions on looking at this are:

 - the image map has to be an svg
 - the sections to be clicked need to be elements in the svg file
 - the `id` of the elements to be selected need to correspond to the `value` of answer choices

Is that about right?

**Comment by lognaturel** [comment]
That's right. More at https://github.com/opendatakit/xforms-spec/issues/108
