### ISSUE TITLE
Describe how loading external settings works

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#5]
opendatakit/collect#456

**Comment by mish24** [comment]
@lognaturel I am not able to understand this part properly. Any sources you can suggest to clear this?

**Comment by troublemagnet** [comment]
@opendatakit-bot claim

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by ankita240796** [comment]
@lognaturel I was working on this issue but I am having some doubts. Is there any source from where I can get some more info on this issue. :sweat_smile:
