### ISSUE TITLE
Collect form widgets, with XLSForm and XForm details

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#50]
part of #20 

essentially this: https://opendatakit.org/help/form-design/examples/
but:
 - add XLSForm details
 - include newer widgets not currently documented 
 - better screenshots (?)

**Comment by lognaturel** [comment]
I'd say "better screenshots (!)" ;)

I do think it would be great to have better screenshots that match the current interface. I find that the best way to take screenshots is [through adb](https://blog.shvetsov.com/2013/02/grab-android-screenshot-to-computer-via.html). It might be good to build a little script or bash alias or something to capture the screen, name it appropriately and pull it to the current directory. I'm imagining I'd do something like `screencap string-widget` and I'd end up with a `string-widget.jpg` file in my current directory.

**Comment by adammichaelwood** [comment]
You are so awesome! I was just looking into the best way to do Android screenshots.
Thanks.

**Comment by lognaturel** [comment]
If you make a script/alias, would be great to have in a contributor guide!

**Comment by adammichaelwood** [comment]
screenshot scripting now works.
