### ISSUE TITLE
Prevent smart quotes in spreadsheet samples

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#513]
I noticed reviewing @jbeorse's PR that all quotes and ticks in spreadsheet samples seem to be rendered as smart quotes. That means samples can't be used from copying and pasting without replacing the quote types.

**Comment by adammichaelwood** [comment]
Code literal blocks shouldn't render to smart quotes already.
If that's happening, it's a bug somewhere.

**Comment by lognaturel** [comment]
That’s great! I noticed it in survey spreadsheet tables so perhaps that’s the change that needs to happen.

**Comment by adammichaelwood** [comment]
Can you point to a file and line number?

**Comment by adammichaelwood** [comment]
Oh, I see. 
I misunderstood your original comment. 
`code-block` sections are not processed by the smartquotes feature, but `csvtable` apparently are.
So this is expected behavior, but --- I take it --- unwelcome. 

The example you gave seems like a harmless case.
Are there specific uses where it is a problem?

**Comment by adammichaelwood** [comment]
I have asked around and Googled a bit. 

There doesn't seem to be a built-in way to add to the built-in list of excluded blocks.
(It might still be possible.)

But...

We have a style guide injunction against quote marks in prose, as there are very few cases where they are needed. We have a few cases of quote marks --- all some version of "scare quotes" --- but they could stand to get written out.

So I wonder if the easiest solution is to just disable smart quotes altogether.

**Comment by lognaturel** [comment]
I'd be very happy for smart quotes to be disabled. 

I especially found it problematic in https://github.com/jbeorse/docs/blob/57381eb4768cdfd30fe3d9f596db7f6feba393b5/src/xlsx-converter-using.rst because there are so many examples that include ticks and quotes.
