### ISSUE TITLE
Describe admin settings menu and how it's typically used

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#54]
opendatakit/collect#1306 - it's not all that clear

This may exist somewhere but I'm not immediately finding it.

**Comment by troublemagnet** [comment]
@adammichaelwood  May I work on this if @mish24 is busy on some other issue?

**Comment by adammichaelwood** [comment]
Yeah. @mish24's commit related to this wasn't actually what we were thinking was needed here.

I think what would be good is a single doc, in the *Collect* section, that simply enumerates each menu  and it's items. So there's a section for the Collect Home screen, and it lists each item there and what it does, then a section for General Settings, and a section for Admin Settings. 

IF a menu item opens a new menu, that menu could have it's own subsection, listing out its content and what they do.

The trick here is to be as organized and clear/concise as possible. 
(This, along with form widgets screen shotting, is something that could be automated in the future, so you want a logical , hierarchical structure as much as possible.)
