### ISSUE TITLE
Add footer with log issue

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#55]
I was just perusing Kubernetes docs (as one does) and noticed that they have a handy "Create an issue" button at the bottom of the docs page (example [here](https://kubernetes.io/docs/tutorials/kubernetes-basics/)). I think that might be a nice way to get more people involved. Maybe since the ODK audience is less technical the link can say "there's something missing or wrong on this page" or something like that. 

The cool thing is that the issue link can pass on the page that the problem is on so the user doesn't risk forgetting it.

**Comment by ronna** [comment]
We can also have a "Was this information helpful?" at the bottom of the page, with an option to send feedback
example [here](https://support.office.com/en-us/article/Office-is-taking-long-to-install-0f09f357-3fef-42a6-b8aa-cef4c6c44bdf?ui=en-US&rs=en-US&ad=US) (right at the bottom of page)

**Comment by adammichaelwood** [comment]
The "Was it helpful" footer needs to be a separate issue (added, #62), as doing this requires additional work beyond adding a link. We'd also need a collection mechanism for that information.
