### ISSUE TITLE
Include instructions on how to build PDF

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#556]
Currently, only those who know to look in `.circleci/config.yml` can figure out how to build the PDF (#537) . We should include instructions on how to do that.

High-level steps are 
1. Install Tex: https://www.latex-project.org/get/#tex-distributions
1. Run the various build commands to go from a clean checkout to the PDF

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by ankita240796** [comment]
@opendatakit-bot I will be working on it in a few days!

**Comment by ankita240796** [comment]
@opendatakit-bot I will be doing this within a week. I am busy this week due to college industrial trip. Sorry for the delay.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
