### ISSUE TITLE
Include note in the PDF about the content being out of date

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#557]
Currently, the PDF (#537) that is being generated doesn't let users know that it might be out of date. We discussed this in the original issue at https://github.com/opendatakit/docs/issues/271#issuecomment-334850319.

I'd propose a few things...
1. Remove the `Release 1.0` text from the PDF. It makes it seem like things are versioned in an orderly fashion.
1. To let people know that the PDF isn't up-to-date, we could put something in the footer that says 
   > ODK software is always being updated, so this PDF is likely out of date. Get the latest guide at https://docs.opendatakit.org.

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by ankita240796** [comment]
@opendatakit-bot I will be working on it in a few days!

**Comment by ankita240796** [comment]
@opendatakit-bot I will be doing this within a week. I am busy this week due to college industrial trip. Sorry for the delay.
