### ISSUE TITLE
reorganize (and possibly move) form-widgets

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#566]
This was one of the first docs I wrote, and it needs a refresh.
I think I have a clear way to go on this,
but I'm wondering about moving it.

@yanokwa and @lognaturel and I have discussed moving it to Collect's TOC
and I see a certain logic to that, 
but also it seems like info you need when designing a form.

**Comment by yanokwa** [comment]
Don't keep us in the dark! What is the clear way you are thinking about?

**Comment by adammichaelwood** [comment]
Essentially, my thinking is to remove the duplication,
and show appearance variations for each widget type
instead of as a whole separate "Appearance" section.
(And, of course, to remove the XML.)

Which is what I should have done in the first place,
but I didn't know about the all-widget form when I started.
So the end result was like I did the whole thing twice.
(You can really see this in the existing document.)

**Comment by adammichaelwood** [comment]
keep in form building
also include in collect "related topics"

**Comment by adammichaelwood** [comment]
change title to "Question Types"
