### ISSUE TITLE
Printer widget documentation

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#568]
https://opendatakit.org/help/form-design/examples/#printing_widgets

Referenced in [the printer widget section](http://docs.opendatakit.org/form-widgets/#external-printer-widget) of form-widgets.rst

Not sure how relevant/current the info is, but the printer widget is still in all-widgets.

**Comment by lognaturel** [comment]
👍It should all be up to date and ready to migrate over!
