### ISSUE TITLE
Document Aggregate installation

### ISSUE THREAD

**Issue by ronna** [opendatakit/docs#57]
Document aggregate installation:
https://forum.opendatakit.org/t/odk-aggregate-minimum-requirements-for-supporting-packages-java-tomcat-mysql/9345

Current documentation needs updating:
https://opendatakit.org/use/aggregate/

https://github.com/opendatakit/opendatakit/wiki/Aggregate-AWS-Install

**Comment by adammichaelwood** [comment]
This would be a great item for you to take on @ronna

**Comment by ankita240796** [comment]
Do we require a new doc on Aggregate Installation?

**Comment by ankita240796** [comment]
@adammichaelwood Can you tell me what exactly is needed in this doc?

**Comment by adammichaelwood** [comment]
A doc on installing Aggregate.

 - This will be the first new doc in a new toc directive for Aggregate
 - It would be great to have a page before install, in that TOC, with a brief overview of Aggregate, like we have for Collect

The install doc should describe ways to install Aggregate, and the easiest way to start is to follow existing install instructions and copy/edit/rewrite as needed.

The *recommended* installation is via Google app engine. Those instructions exist already, and I have followed them successfully. You should be able to do the same and then fold that info into this repo.

It would also be good to fold in the AWS and other install instructions. I think there is also a docker image than can be deployed.

----
So... there's a lot of ways to install Aggregate.
If you don't feel like you can cover all of them, that's okay. Start the doc and cover the Google App Engine stuff, and do a PR. We can add more as we go.

**Comment by ankita240796** [comment]
I got that @adammichaelwood . Thanks!

**Comment by ankita240796** [comment]
@opendatakit-bot claim
