### ISSUE TITLE
Link each page to GitHub source for editing

### ISSUE THREAD

**Issue by downeym** [opendatakit/docs#571]
Earlier today [in the Slack #docs-code channel (registration required)](https://opendatakit.slack.com/archives/C5KCRU1L1/p1520954667000306), a few of us (specifically, me, @adammichaelwood, and @lognaturel) were discussing usefulness of linking directly to docs source files on GitHub for simple edits. This workflow could ostensibly allow someone to make minor changes by editing the file using the GitHub web UI, then submitting a pull request without having to run anything on their desktop.

I'm not exactly sure how we're implementing the [Sphinx Read The Docs theme](https://github.com/snide/sphinx_rtd_theme) here, but in theory it should be able to get some configuration items to change the "View Source" link in the upper right of each page to an ":octocat:  Edit on GitHub" button. https://docs.readthedocs.io/en/latest/vcs.html describes how this would be done in a standard Read The Docs deployment; it'd probably need adjustments to work here.

So the questions are:

1. Is this approach one that ODK should adopt?
2. How to implement such a button within the theme?

**Comment by jaredbhatti** [comment]
Yes. 1000 times yes. Otherwise, I'm spending time trying to hunt down the file in the repo to edit. 

Really, anything we can do to reduce the "time to dopamine" for our contributors is a good thing.
