### ISSUE TITLE
makefile to empty build directories, not delete altogether

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#578]
Currently, the makefile deletes the output directories entirely and recreates them.

This requires me to then stop my local Python server, cd up out of the dir, cd back into it, and restart the server.

Is it possible for the makefiles to *empty* the directories but leave them in place?

@jbeorse

**Comment by jbeorse** [comment]
Hmm. You want the makefiles to leave the odk1-build directory correct? But still remove the tmp directories I assume. The tradeoff is a more cluttered home directory, but it seems safe to me as I think we already have entries in the .gitignore file. If its messing with your workflow to delete the build directories I think we should probably go ahead and delete them. 

I am imaging this change as follows:

1. `make clean` continues to work as normal and truly deletes all the build and tmp folders.
2. Create new softer clean, something like `make clean_files`. This will delete the tmp folders and clear out the files in the build directory, but it will leave the build directory itself.
3. Adjust the `make odk1` and `make odk2` tasks to use the softer version of this clean.

Does this fit your needs?

**Comment by jbeorse** [comment]
Addressed with https://github.com/opendatakit/docs/pull/586.
