### ISSUE TITLE
Add documentation for ODK Aggregate VM

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#579]
I've attached a good starting point from the old [readme.txt](https://github.com/opendatakit/docs/files/1826079/readme.txt).

I think we need to have information on:
1. Basic usage. I think we have this in the readme.
1. How to log into root after initial install and change that password for security.
1. How to reconfigure the FQDN and why that's important
1. Pointer to Virtualbox documentation on changing ports.

I think we need to remove the notes on:
* Versions of Virtualbox.
* The speed of the VM
* The network not assigning IPs
* The VM address being the server URL
* The stuff on external servers (this is fixed by allowing people to use the FQDN).

**Comment by yanokwa** [comment]
I think these docs should probably go under the Installing Aggregate section. Maybe with the title "Installing the VM" or something like that.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by ggalmazor** [comment]
@opendatakit-bot claim --force

**Comment by yanokwa** [comment]
Here's what I'm bundling with the beta. It should be an even better start! [readme.txt](https://github.com/opendatakit/docs/files/1826295/readme.txt)

**Comment by ggalmazor** [comment]
There's already a [ODK Aggregate Virtual Machine](http://docs.opendatakit.org/aggregate-vm/#odk-aggregate-virtual-machine)

I guess the best would be to update that section.
