### ISSUE TITLE
Add Enketo screen shots to Widget guide

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#58]
work on a complete widget guide is in progress, but first pass is only ODK Collect screen shots. Add Enketo screen shots would be good too.

**Comment by lognaturel** [comment]
My sense is that we should start by only documenting the ODK core tools for now and then we can talk with others in the ecosystem about how they'd like their projects represented and potentially documented.

**Comment by yanokwa** [comment]
Agreed with @lognaturel and so I'm closing this issue.
