### ISSUE TITLE
Document navigation setting

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#6]
We've been hearing about groups that use ODK to survey the general population. They'll do things like hand tablets around rather than using trained enumerators. One challenge they face is that people don't know to swipe between questions. It seems they should probably be using the "use swipes and buttons" navigation setting.

It would of course be helpful to have documentation on all the settings. But for this one specifically, it would be helpful if it were included in "advice for surveys without enumerators" or something like that.

**Comment by troublemagnet** [comment]
@adammichaelwood  this has been done too.
