### ISSUE TITLE
Android-level security recommendations

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#61]
For example, if enumerators are able to install apps, they can install camera apps that may let them bypass certain requirements (see [here](https://forum.opendatakit.org/t/disable-choosing-an-image-video-or-audio/9338)).

Another example -- turning on Android-level data encryption means when the device is locked, no one can see the data. It's an easier alternative to using encrypted forms that offers most of the benefits.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
