### ISSUE TITLE
Add "Was this helpful?" or other feedback mechanism on docs page

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#62]
add from @ronna comment on #55:

> We can also have a "Was this information helpful?" at the bottom of the page, with an option to send feedback
> example [here](https://support.office.com/en-us/article/Office-is-taking-long-to-install-0f09f357-3fef-42a6-b8aa-cef4c6c44bdf) (right at the bottom of page)

**Comment by adammichaelwood** [comment]
So... what about a comment section?

**Comment by smartyrad** [comment]
@adammichaelwood The issue with a comment section would probably be that it would clutter the documentation page. 

However, another suggestion would probably be that we create a separate post on Open Data Kit Forums specifically for such feedback. So, when the user clicks "No", we could directly redirect the user to that post. This would save us a lot of trouble from an implementation point of view and would also serve our purpose. What do you feel?

**Comment by adammichaelwood** [comment]
I'm still not a fan of this idea. I just think "Was it helpful?" isn't helpful.

Good point on the comments. I don't think we want to be in the business of fighting comment spam and moderating discussion.

We could add a link to the forum in/near the "file an issue" note, though.

**Comment by smartyrad** [comment]
@adammichaelwood  Makes sense. We could add a line below/above the file an issue line which goes something like this : 
"If you would have any feedback regarding this documentation, please share in this ODK Forum thread"
 maybe?

**Comment by adammichaelwood** [comment]
How about:

> If you still need help, you can ask support questions in the [ODK Forum](https://forum.opendatakit.org/).

Someone could add this under the File and Issue text. The weird broken-up style used for that is fine, and we'll fix them both when someone figures out how to solve #141 .

**Comment by ankita240796** [comment]
I'd like to work on this.

**Comment by adammichaelwood** [comment]
Great. Please claim the issue.

**Comment by ankita240796** [comment]
opendatakit-bot claim

**Comment by ankita240796** [comment]
@opendatakit-bot claim
