### ISSUE TITLE
Reduce the size of PNGs before publishing

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#64]
Currently, the images in the repo are large (as far as bits). For example, `_images/annotate-1.png` is 1.7 MB, but running it through [ImageOptim](https://imageoptim.com/) at 80% compression brings it down to 595 KB. Reducing the size of the images makes for much faster loading (important in the areas where ODK is used) and it also saves us money. 

An ideal solution to this problem would compress the images as part of the sphinx build process.

**Comment by adammichaelwood** [comment]
> An ideal solution to this problem would compress the images as part of the sphinx build process

So that would just be taken care of on the circleci end, yes?
If we switch to glfs (re: #65 ) contributors don't need to worry about running compression locally.

Yes?

**Comment by yanokwa** [comment]
I'm going to propose a few things.

1. We should run lossless compression on all source images because it is lossless and there's no real reason to have massive source images. This should be done locally and be in the contribution guide. We should open a new issue for a tool recommendation for lossless png/jpg and instructions for the contribution guide.

1. On publication, we should run lossy, but sane compression on those images. This needs to be done via CI and the smaller the source images, the faster this will run. I will submit a PR to do this with pnquant on pngs, but we should also open an issue for jpgs.
