### ISSUE TITLE
When publishing, please indicate how often (timing of) Aggregate will push data

### ISSUE THREAD

**Issue by Ken14** [opendatakit/docs#641]
March 12, 2018 Documentation

Chapter 8

Because of limits with Google Sheets cell counts, it may be necessary to restart/republish data during a live campaign.  Is it opportunistic (random), every 5 minutes, 10, ...?  

The Aggregate documentation should indicate the timing parameters of how often data will be pushed. If the survey is of limited duration, this may not matter. If a survey is being used over many days, it is useful in determining if a aggregate publishing of data is the correct procedure, using a timed operation from Briefcase or a manual intervention on Aggregate (to a new file/caveats about duplicates). If this timing is something that should not be counted on, this should also be noted.

Since this Briefcase operation may be done by non-technical people, it might be useful to publish example scripts that show how this might be done on Windows (powershell/R Script) or on *nix (shell/cron).

**Comment by yanokwa** [comment]
@ggalmazor You were just in this code. Do you know?

**Comment by ggalmazor** [comment]
I can find out. Let me get back to you with this.

**Comment by ggalmazor** [comment]
According to the comments on the `WatchDog` interface: 

> Watchdog has two radically divergent implementations. 
> - On Tomcat, WatchdogWorkerImpl is executed using the spring task framework. Watchdog implementation manipulates the Executor from that framework.
> - On GAE, the WatchdogWorkerImpl is fired by either a cron, or through website activity, or via deferred task executions.
>
> If there is no pending work, the Watchdog is re-fired every **15 minutes**.
> If there is work, then Watchdog is re-fired every **30 seconds** until there is no pending work.

**Comment by ggalmazor** [comment]
@opendatakit-bot claim

**Comment by yanokwa** [comment]
@ggalmazor I think if we can stick this as a first bullet in the note at https://docs.opendatakit.org/aggregate-data-access/#publish-data. My understanding is that 
> Publishing attempts happen at most every 15 minutes. If there are pending submissions to publish, there will be attempts at most every 30 seconds until there are no pending submissions.

That sound accurate?

**Comment by ggalmazor** [comment]
Sounds good. I'll create a PR
