### ISSUE TITLE
Referencing answers from previous iteration example has several problems

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#661]
https://docs.opendatakit.org/form-repeats/#referencing-answers-from-the-previous-iteration

The calculation is in the wrong column, the parens for the calculated expression aren't right and defaults can't be dynamic!

@adammichaelwood @yanokwa are y'all making sure these examples run on actual devices when you do review? Perhaps we should make that part of either the PR template or a review checklist so we can be sure examples are authoritative.

**Comment by adammichaelwood** [comment]
I created live examples in a form, made sure they worked (I thought I did, anyway), and then transferred that info into the doc. 
I'm not surprised errors crept in to that process. It would be amazing to create a way to text form samples out of csv-tables. 

In the mean time, i will address this specific issue right away.

**Comment by adammichaelwood** [comment]
> defaults can't be dynamic

stuff just ended up in the wrong column...

**Comment by adammichaelwood** [comment]
> defaults can't be dynamic

really?

**Comment by lognaturel** [comment]
It happens! Sounds like a sound process otherwise.

Defaults must be static values. The challenge otherwise is when the default gets evaluated and when the user has control over the value. In your example, the value for `${previous_school}` can only be computed once the repeat in question is generated. Defaults are set once at launch time.

If you're interested in a way to do something like dynamic defaults, see https://forum.opendatakit.org/t/is-it-possible-to-set-a-default-value-for-a-decimal-question-using-the-calculate-column/12141/3. It's a common ask so perhaps it would be a good recipe to add in the defaults section.

**Comment by adammichaelwood** [comment]
this whole example is a fail, though... it isn't in my working test form
(Something similar is... but I think I lost my mind and went a different direction when writing.)

So... since this whole example relies on a dynamic default value...
do you have a good example use case for referencing a previous iteration's value?

**Comment by lognaturel** [comment]
I can't really think of one! It's not something I've ever needed to do. So perhaps the simplest solution is to remove that section and reintroduce it if we come across a good example.

If you're looking for something else to do with `position`, selecting a random member of a repeat is a common one.
