### ISSUE TITLE
Add note about defaults being static values only, possibly with a workaround

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#664]
Defaults are set once at form beginning so they can't be dynamic. The barrier to making them dynamic is that often the values that would want to be used as defaults are changing and it's not clear when they should update and when the user should have control.

https://forum.opendatakit.org/t/is-it-possible-to-set-a-default-value-for-a-decimal-question-using-the-calculate-column/12141/3 shows one approach that sets the dynamic default whenever the target value is blank. Once it's set, it can be modified by the user. With this approach, the target value cannot ever be blank (it's either the default or a value set by the user).

**Comment by adammichaelwood** [comment]
Correct me if this is wrong, but --- as I understand this proposed solution, the "default" value only matters on the "back end". From the user's point of view, the question itself does not have a visible default value?

**Comment by lognaturel** [comment]
It does show up for the user! The trick is that we’re using a calculation for a field that has a user control (decimal in that case). And because we use once, it only gets evaluated if the field is blank so user modifications are safe. There’s a form you can try at https://forum.opendatakit.org/t/timestamping-responses/11825/3

**Comment by adammichaelwood** [comment]
> It does show up for the user

Right, but only in a note. You can't use this trick to populate the answer field of a question.

So you might combine it with a hint, like: *Leave blank for ${default-value}*

**Comment by lognaturel** [comment]
Give it a try and see what you think. I believe it’s what most people have in mind when they want dynamic defaults. The first time the user sees the target field, it has the same value as the source field. They can them either leave it as-is or modify it.

**Comment by lognaturel** [comment]
Oh, I see, the timestamp one doesn’t need user modification so you’ll want to recreate my suggestion from the original post.

**Comment by adammichaelwood** [comment]
So, an interesting side note here is that if you try to use this dynamic default technique *in the context of using the previous iteration's answer as the default in the current iteration* (that is --- my origin a example of assuming the current child goes to the same school as the previous child) JavaRosa thinks that there is a circular reference. (Even though the reference is to the previous iteration so isn't *actually* circular.)
