### ISSUE TITLE
Widget that allows attaching files of any type

### ISSUE THREAD

**Issue by grzesiek2010** [opendatakit/docs#667]
On the Collect's side, we are working on `ArbitratyFileWidget` https://github.com/opendatakit/collect/issues/2135 
It's a widget that allows selecting any type of file.

Once it's merged it should be added to the doc also.

**Comment by lognaturel** [comment]
This will be in the next Collect release (v1.15) and would be good to have documented. 

I think it's important to include a warning that currently any file type can be uploaded and that this could potentially include malicious files. Form designers should not use this type if enumerators are not trusted. If they download the files to a local computer, they should run an antivirus scan on them and/or verify that they are all safe file types (e.g. not exe, ini, etc).

**Comment by adammichaelwood** [comment]
From the various conversations, it looks like the user can specify file types. But I'm not clear on the format for doing so.

**Comment by lognaturel** [comment]
Reopening because the warning mentioned at https://github.com/opendatakit/docs/issues/667#issuecomment-387118912 still needs to be added.
