### ISSUE TITLE
Reduce the size of JPEGs before publishing

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#68]
On publication, we should run lossy compression with sane defaults on all jpgs.

I believe the best way to do this is likely to use mozjpeg. We'll likely have to install from source and https://nystudio107.com/blog/installing-mozjpeg-on-ubuntu-16-04-forge is a decent guide.

**Comment by yanokwa** [comment]
We don't do this. I don't think we should. Instead, I propose we
* convert the handful of jpgs/jpegs we have to png
* add language to the contributing guide to tell people to use pngs when possible.

If you agree, close this issue and file an issue for both.

**Comment by adammichaelwood** [comment]
This makes sense to me.
