### ISSUE TITLE
How much HTML to document and where to put it.

### ISSUE THREAD

**Issue by MartijnR** [opendatakit/docs#699]
Maybe this is no longer true after the latest markdown updates (ported from Enketo) in Collect which covered various header issues:
> If a Markdown header is used, the label or hint can only be one line of text. Line breaks in the XLSForm cell will break the header styling.

Also, just FWIW, it would make me very happy if the rogue HTML support was not documented (except for `<span>`)~~. This was an unhappy event of the dark past and it was more or less agreed not to document this if I remember correctly~~, so we don't have to explain to users that one type of formatting doesn't work in e.g. Enketo.

**Comment by adammichaelwood** [comment]
From #700:

>I don't have a strong opinion on the development issue. (Though --- if I had one --- my preference would be to support HTML as much as possible/reasonable.)
>
>I do have a strong opinion about documentation: We should document what is there. If what is there changes, we should change the documentation.
>
>Perhaps mention of (limited) HTML support would be better in another place, instead of in styling. I'm planning to do a small "anatomy of a form question" section, which will include things like "don't put spaces in name". Perhaps that is the right place to mention --- without examples that encourage use --- that Collect supports this small list of HTML tags. (Along with the notice that this is not supported in Enketo.)

**Comment by yanokwa** [comment]
My rough proposal here is that we say...
1. We support and recommend Markdown as the way to style.
1. Add a section under Markdown called "Inline HTML"  (because Markdown does support inline HTML). That section will warn that use of HTML outside of <span> is not ODK standards compliant and it's not recommended. We also note that depending your version of Android some tags might work (and link to latest Android source), so stay away.

**Comment by MartijnR** [comment]
Sounds good to me and will be helpful to users. Maybe good to separate `<span>` plus likely `<sub>` and `<sup>` from the other tags, but that may also makes things too confusing again.

P.S when looking at the ODK Collect code, I think you only support `color` and `font-family` rules as acceptable content of the `style` attribute in a `<span>` (which would be great to add to documentation too - Enketo hasn't implemented such a style filter (unfortunately) so I just won't document other style rules).
