### ISSUE TITLE
pyxform: describe how to get the command-line tool

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#7]
`pyxform` is used as an underlying library in several form-conversion tools.

For some people, the command-line tool can be convenient and it's easy to install with `pip install pyxform`.

https://github.com/XLSForm/pyxform

**Comment by troublemagnet** [comment]
@adammichaelwood sir only the installation instructions have to be documented or additional details about pyxform too?

**Comment by Divya063** [comment]
@lognaturel Can I work on this?

**Comment by lognaturel** [comment]
I think what needs to be included are the first two sentences from the README ("pyxform is a Python library that makes writing XForms for ODK Collect and enketo easy by converting XLS(X) spreadsheets into XForms. It is used as a library in a number of tools including the ODK online converter and Ona."), a brief sentence describing that the tool can also be run directly from the command line, the `pip` install command and a link to the repository. Some thought will be required to figure out where it should go. Find the most logical place for now and it can be moved later.

@troublemagnet sorry I didn't see your message earlier! Let's let @Divya063 take a stab at this one.

**Comment by Divya063** [comment]
@lognaturel Thanks for the information :smile:

**Comment by Divya063** [comment]
@opendatakit-bot claim
