### ISSUE TITLE
Add note that default values should not have quotes around them

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#702]
This appears to have caused confusion with dates - https://github.com/opendatakit/collect/issues/95. I can imagine someone wanting to put quotes around other data types too so it's a quick note that applies across the board.

**Comment by adammichaelwood** [comment]
That was a lot of back and forth in the issue, but --- I want to make sure I understand --- the point is simply:

Default value is literal (not an expression), so quotes will be interpreted as part of the value. So don't use them. (Except for strings if you literally want the quotes as part of the value... for some reason.)

yes?

**Comment by lognaturel** [comment]
Precisely!
