### ISSUE TITLE
Update "Pushing forms to Aggregate" Briefcase section

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/docs#703]
After the PR https://github.com/opendatakit/briefcase/pull/461 is merged, this section and maybe others have to be updated.

Changes are:
- Now Briefcase won't push blank forms if they're already present on the destination server
- The CLI has a new flag to force sending the blank forms regardless
- The GUI will always send the blank forms regardless (no option to configure this yet on the GUI)

**Comment by yanokwa** [comment]
Closed by #842
