### ISSUE TITLE
Archive a snapshot of the ODK website

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#706]
https://github.com/opendatakit/docs/issues/668 reminds me that we might have gaps in the ODK documentation migration. I  think we should grab a DB and FS snapshot of the ODK website and have that in some repo.

**Comment by adammichaelwood** [comment]
@yanokwa 
Was this done, or is it still possible to do?

(If the host is still up, maybe it can be exposed at for example old.opendatakit.org)

**Comment by yanokwa** [comment]
The host is at 128.208.2.75, but it's not long for this world. I've put the XML and uploads as a v0.0.0 release of the website here: https://github.com/opendatakit/website/releases/tag/v0.0.0
