### ISSUE TITLE
Update Briefcase Pull/Push sources

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/docs#711]
After PRs https://github.com/opendatakit/briefcase/pull/463 and https://github.com/opendatakit/briefcase/pull/466, the available sources for pulling and pushing forms have changed:

**Pull sources**
- Aggregate
- Custom Directory (Collect storage directory)
- Form in Computer

**Push sources**
- Aggregate

Some [docs page "Using ODK Briefcase"](https://docs.opendatakit.org/briefcase-using) sections should be updated and a new one created for the new source "Form in Computer"

**Comment by yanokwa** [comment]
Closed by #842
