### ISSUE TITLE
use of == as comparison operator

### ISSUE THREAD

**Issue by atl2017** [opendatakit/docs#713]
In documentation [using-relevants-to-limit-repetitions](https://docs.opendatakit.org/form-repeats/#using-relevants-to-limit-repetitions) you use double =, but I havent seen this as a operator. Is it valis for comparison?

Example
if(${meal_preference} == 'chicken', 1, 0 )

**Comment by adammichaelwood** [comment]
Thanks for the catch.

This is a typo, caused by my being more familiar with Python,
which uses the `==` for comparison and reserves `=` for assignment.
