### ISSUE TITLE
Aggregate install on Mac requires JDK, not JRE

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#730]
https://forum.opendatakit.org/t/installing-odk-aggregate-google-app-engine-on-mac/13327/4

I'm pretty sure this is Mac only.

**Comment by adammichaelwood** [comment]
So this?
http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

Or should we suggest 10?
http://www.oracle.com/technetwork/java/javase/downloads/jdk10-downloads-4416644.html

Is there any reason this wouldn't also be needed on Windows and Linux?

**Comment by yanokwa** [comment]
I think recommending the latest JRE is a good idea for all the Java apps (Briefcase, Aggregate, Validate). The JDK requirement seems to be a Mac only thing, but it'd be good to actually check all of this.

@kkrawczyk123 (or @ggalmazor) can you confirm that a Java 10 JRE install (not JDK) for Briefcase and Aggregate works on Windows and Linux?  What about on a Mac?

**Comment by jaredbhatti** [comment]
GAE standard requires the SE 8 JDK regardless of OS. (https://cloud.google.com/appengine/docs/standard/java/quickstart)

Tomcat docs also indicate that a JDK is required (https://tomcat.apache.org/tomcat-9.0-doc/building.html)

**Comment by jaredbhatti** [comment]
From @yanokwa  

The Aggregate installer produces a WAR that you hand over to Tomcat to install. But Tomcat may or may not be installed on the same computer you are using to run the installer. So *technically* you don't need the JDK, but we should be on the safe side and specify JDK installation.
