### ISSUE TITLE
Documentation on how to expand the character limit

### ISSUE THREAD

**Issue by michaeledwardmarks** [opendatakit/docs#745]
This is a commonly requested behaviour by users (which is also easy to implement) so it would be great if this could be included in the documentation around XLSForm design

**Comment by lognaturel** [comment]
@michaeledwardmarks thanks for reporting this omission! You're talking about Aggregate's 255 character truncation for text fields, right? This was the previous help text:

> In ODK Aggregate 1.x, you can supply an attribute to the to specify the maximum number of characters used to store a string field; by default, the datastore layer limits strings to 255 characters or less. If a submission has data beyond this length, it is silently truncated upon submission.

> Specifying a value less than 255 can significantly improve the storage efficiency of the database layer. You can also specify a value greater than 255, up to a maximum of about 16000 UTF-8 characters. The higher you set this value, the worse the storage efficiency within the datastore.

> To set the string length:

> In the header of the form definition, add a xmlns alias for odk (shown added as the last xmlns alias at the bottom of the tag):

> xmlns:h="http://www.w3.org/1999/xhtml" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:jr="http://openrosa.org/javarosa" xmlns:odk="http://www.opendatakit.org/xforms" ><h:head>
Then, in the bind, you can define an odk:length attribute to specify the length of a string field. Length can be specified for barcode, select1 and string fields. Multi-selects (select) fields have a 255 character maximum length for each selection value (and selection values must not contain whitespace); there are no limits to the number of choices that may be selected within a multi-select.

> Specifying a value less than 255 can significantly improve the storage efficiency of the database layer.

I would remove this or say it "may improve the storage efficiency when using MySQL." It does not with Postgres these days.

The XML content can go and be replaced with `bind::odk:length` in XLSForm.

**Comment by michaeledwardmarks** [comment]
Yes exactly 
1) Guidance in the aggregate section on docs for the back end user
2) Guidance in the collect / XLSForm section saying
a) Default is 255 
b) This is how you can change using bind::odk:length
c) if you do b make you tell your server person so they can amend the server settings

**Comment by lognaturel** [comment]
> if you do b make you tell your server person so they can amend the server settings

@michaeledwardmarks can you say more about this? I think it may have been required for versions of Aggregate > 5 years old but now the provided length is read when the form is uploaded and the db table size is adjusted accordingly. In what case would a server setting need to change?

Pull request up at #835.

**Comment by michaeledwardmarks** [comment]
> I think it may have been required for versions of Aggregate > 5 years old but now the provided length is read when the form is uploaded and the db table size is adjusted accordingly.

I think it was more recent than that but happy to hear you can just set in the form (we certainly had this issue say 3 years ago).
