### ISSUE TITLE
No docs on how to include images or audio as part of the question

### ISSUE THREAD

**Issue by smoyth** [opendatakit/docs#749]
At least I couldn't find them? It's covered on the XLSForm site but not the ODK docs. Should it be?

Thanks!

**Comment by yanokwa** [comment]
Does https://docs.opendatakit.org/form-question-types/#including-images-as-choices help? Maybe we can broaden it to media?

**Comment by yanokwa** [comment]
Can you submit a PR (and offer feedback on how easy the docs are to contribute to)?

**Comment by smoyth** [comment]
I would love to but it might be awhile. Pretty busy at the moment. In the meantime if someone else picks it up I'd be fine with that.

**Comment by danbjoseph** [comment]
you mention the XLSForm site, are you referring to http://xlsform.org/en/#media ?
> You can include questions in your form that display images or that play video or audio files. If using the ODK mobile client for form submission, you need to put the media files that you want to include in the /odk/forms/formname-media folder on your phone, and then reference the exact file name in the media column in your form. 

(the above being what you'd like to see in the ODK docs?)

**Comment by smoyth** [comment]
@danbjoseph Yes that's the gist of it!

**Comment by smoyth** [comment]
... I'm not sure where it would go in the docs since it's not specific to any particular question type.

**Comment by adammichaelwood** [comment]
Two less-than-ideal suggestions, based on current organization of form building section:

A. Write a standalone document that explains how to put images and other media into the prompt (`form-media.rst` or `form-prompts.rst` maybe (?) --- depending on what direction it seems the document might evolve)
     - Add it to the [tips and best practices TOC](https://docs.opendatakit.org/form-best-practices/)
  
B. Add it as a section to [Form Styling](https://docs.opendatakit.org/form-styling/).


Even if you went with A, I would probably mention it somewhere in the text of Form Styling.

**Comment by lognaturel** [comment]
https://docs.opendatakit.org/form-language/ does very briefly mention `media::` but doesn't show an example. As part of or in addition to adding some information about `media::`, it would be good to show a multi-lingual media example.
