### ISSUE TITLE
Update instructions to install Aggregate on Google App Engine

### ISSUE THREAD

**Issue by ggalmazor** [opendatakit/docs#753]
I've detected some flaws in the current instructions:
- Some of the screens have changed and the steps don't match the exact path a user would have to follow.
- Especially confusing: in one step the user must select a role for some credentials and no role is specified in the instructions.
  - Tested and working roles are: AppEngine admin
  - We should test if setting no roles works as well
- Important steps missing:
  - Clear history/cache after setting Google API credentials. Otherwise, the dev version could be used until the browser invalidates the cached version

**Comment by iamnarendrasingh** [comment]
We need to add 2 steps as soon as we create a project on google cloud.  We need to launch cloud console and then need to enter "glcoud app create" 
![firefox_2018-07-27_20-22-56](https://user-images.githubusercontent.com/5762689/43721871-a045cb96-99b1-11e8-9c51-f3718017b350.png)

and then need to select server location once we will select server location we need to enter one more command and that command is "gcloud app deploy ". Looks like this 

![firefox_2018-07-27_20-24-35](https://user-images.githubusercontent.com/5762689/43721972-db2a5b46-99b1-11e8-9f0e-4072b5c9e754.png)

And you are good to go. These are 2 new changes which we need to update in docs.

Best,
Narendra Singh

**Comment by iamnarendrasingh** [comment]
Hi, 

I also made a video on how can a person set up ODK Server on google cloud app engine.
Below is the link of that video:
https://www.youtube.com/watch?v=2VNAQDl20I0
I do have a presentation on this that how can we install ODK Aggregate and both are updated.

Best,
Narendra Singh

**Comment by ggalmazor** [comment]
Hi, Narendra!

Thanks for the documentation and the video! All these information gathering will be really useful when updating the docs.

I think the part that goes through the IAM and Service Accounts needs some updating too. @kkrawczyk123 and I detected that the instructions don't quite match the actual process one has to follow to set that up.

**Comment by iamnarendrasingh** [comment]
I set up more than 5 servers with the same method and with the help of this I made this presenatation.

Best,
Narendra Singh

**Comment by ggalmazor** [comment]
Great! Just to be clear, in my last comment I was referring to defects found on the current docs, not your video ;)

The goal of this issue is to gather info on all the things that should be fixed in order to make the actual changes in the docs easier.

**Comment by iamnarendrasingh** [comment]
@iamnarendrasingh  claim

**Comment by ggalmazor** [comment]
Closing this issue since we don't support AppEngine anymore
