### ISSUE TITLE
Document send via SMS

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#781]
- How to configure Collect
- Form design
- Tips on setting up a receiver
- Limitations
- Alternatives (SMS from form)

**Comment by lognaturel** [comment]
From #782 - "All screenshots of Server settings will need to be updated."

I believe all of the information is there but the screenshots may now be misleading.

**Comment by atl2017** [comment]
Due to [ODK Collect  release 1.20.0](https://forum.opendatakit.org/t/removal-of-sending-submissions-via-sms-in-collect/17973) we suggest to hide [send via SMS documentation](https://docs.opendatakit.org/collect-sms-submissions/)

**Comment by yanokwa** [comment]
Thanks for letting us know! I've filed sent in a PR at https://github.com/opendatakit/docs/pull/984.
