### ISSUE TITLE
Collect development : images in QuestionWidgets

### ISSUE THREAD

**Issue by shobhitagarwal1612** [opendatakit/docs#8]
If we want to use `imageView`, `imageButton` in Widgets then we should avoid adding the image to the `xml` layout. The image should be added dynamically using `setBackgroundResource()` so that the garbage collector can recycle the bitmaps and prevent the activity from crashing (caused while trying to use a recycled bitmap).

**Comment by adammichaelwood** [comment]
@lognaturel 
This seems in the wrong place. Yes?

**Comment by lognaturel** [comment]
It's something to remember to add to the Collect dev docs. Is there another place you'd like it to go?

**Comment by adammichaelwood** [comment]
Closing, as dev docs are not here.
@lognaturel Is this taken care of on the dev side? Is there a good place I can add it so it doesn't get lost?
