### ISSUE TITLE
Add documentation about image size and compression for doc contributions

### ISSUE THREAD

**Issue by danbjoseph** [opendatakit/docs#841]
- In the details for contributors there should be something about recommended size to aim for with images and suggestions on a few workflows to shrink files (ImageOptim, ImageMagick, Photoshop, etc.)? See #840  
- Also, a note about image file type? Should be PNG? 
- Recommendations about how to have small file size? For example, use clipart (with compatible license) instead of photos if creating an example question using images, strip unnecessary exif data like GPS, etc.
![screen shot 2018-09-06 at 9 05 21 am](https://user-images.githubusercontent.com/4806884/45159241-3cf94980-b1b4-11e8-9a99-adf55d0641c4.png)

**Comment by lognaturel** [comment]
I really hate to have more things for contributors to think about! Any chance this can be part of the publishing pipeline?

**Comment by lognaturel** [comment]
I meant automating the resizing and compression as part of CI. I guess this would either mean CI would need to commit changes or the repo versions would be bigger than the published versions.

**Comment by yanokwa** [comment]
I'm no on doing this in CI for the reasons you noted. It feels dangerous to give CI commit privileges to master. I don't even know how to automate that. I'd rather give first time committers a pass if they don't do it, come over the top with a PR, and ask them to do it next time.

**Comment by danbjoseph** [comment]
seems like #823 might help with some of this

> has instructions on all this

yep, darn, didn't look hard enough. the detail of the contributor docs is wonderful but that does also mean it can sometimes be hard to discover if a particular topic exists. 

> the handful of things that people need to know to get their first contribution. That will let them pattern match without reading all the contribution docs.

i also like this idea

**Comment by yanokwa** [comment]
Since we have documentation about image size and compression, I'm going to close this issue and continue the higher level conversation at #823.
