### ISSUE TITLE
BUG - MBTiles link in collect-offline-maps goes wrong

### ISSUE THREAD

**Issue by atl2017** [opendatakit/docs#846]
https://docs.opendatakit.org/collect-offline-maps/

MBTiles link in collect-offline-maps goes to unbroken link due to extra ")" https://github.com/mapbox/mbtiles-spec). It should be: https://github.com/mapbox/mbtiles-spec  
![image](https://user-images.githubusercontent.com/29519901/45387439-b392ae80-b5db-11e8-8ab0-5a562b603b5b.png)

**Comment by lognaturel** [comment]
Thank you! Would you like to take a try at fixing it? You should be able to click "Edit on GitHub" at the top right, make the change, add a message at the bottom, commit and then create a pull request. It would be helpful to hear from you whether that process is reasonable.

**Comment by atl2017** [comment]
Done! Also for #847
