### ISSUE TITLE
Add front appearance for barcode 

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#853]
As of Collect v1.17.0, the `front` appearance can be used with a barcode question to force the front camera to be used. More info and sample form at https://github.com/opendatakit/collect/pull/2453

This should be added to https://docs.opendatakit.org/form-question-types/#barcode-widget

**Comment by adammichaelwood** [comment]
Should we include details of common use cases?
![photodune-876560-barcode-xs](https://user-images.githubusercontent.com/1776241/45568562-d908fd80-b811-11e8-984d-d18c8171bc81.jpg)

**Comment by lognaturel** [comment]
:D :D :D

**Comment by adammichaelwood** [comment]
(PS Don't search Google for "barcode on face" if you're not ready for some mildly distressing content.)

**Comment by grzesiek2010** [comment]
I'm waiting for review @opendatakit-bot
