### ISSUE TITLE
Convert "App Designer->Pushing and Pulling" Docs Updates

### ISSUE THREAD

**Issue by jbeorse** [opendatakit/docs#861]
In [this forum thread](https://forum.opendatakit.org/t/community-contributions-to-upcoming-odk-2-0-documentation-refresh/11324/8), ODK 2 users have contributed updates to the App Designer documentation. To resolve this issue, the changes outlined in [Pushing and Pulling Files 9.1.18 CGK.docx](https://github.com/opendatakit/docs/files/2413546/Pushing.and.Pulling.Files.9.1.18.CGK.docx) should be implemented on the [corresponding page](https://docs.opendatakit.org/odk2/build-app/#pushing-and-pulling-files).

This issue involves no new copy writing, just implementing existing copy changes in the proper Sphinx syntax.

**Comment by vmaldosan** [comment]
Claim, please.

**Comment by vmaldosan** [comment]
@opendatakit-bot claim, please.
