### ISSUE TITLE
Vid directory like Img directory

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#87]
Right now, vids are in `_static/vid` (see #66 for discussion on this point)

The problem with this is that `_static` is *mostly* used for design-specific things (css, js, logo image), not content. Also, as discussed, this makes img and video weirdly different. (And other content, like downloadable xls, pdf, etc. will also end up in `_static` at some point) (cf. #47)

I propose:

 - create new `vid` dir in root, like `img` dir
 - move current vids and update the markup where they are inserted
 - adjust build so `vid` dir is copied over (I *think* this can be done in Sphinx conf.py, but I have to check -- if not, it'll be a circleci thing)

Then content and design are more clearly separated (and no one will ask or wonder the logo image is in `_static/` instead of `img/`

And, then, for future reference:

 - if we add a sphinx directive for video, the file structure won't need to change, because we've already changed it
 - other downloadable content files can have their own dir (maybe `dl` or `files` or something?)

**Comment by troublemagnet** [comment]
I'd like to work on this, may I?

**Comment by adammichaelwood** [comment]
Sure. This should be pretty easy -- just moving some files around and updating references.

**Comment by adammichaelwood** [comment]
You'll also need to update `./b.sh` to copy the videos over. And @yanokwa will need to update CircleCI

**Comment by adammichaelwood** [comment]
closed via #147
