### ISSUE TITLE
Include OpenRosa documentation

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#9]
https://bitbucket.org/javarosa/javarosa/wiki/OpenRosaAPI -- some of this is obsolete but most of it is still applicable to [ODK JavaRosa](https://github.com/opendatakit/javarosa) which powers Collect. It also describes the interaction between servers and clients in the ecosystem. This is only relevant to developers.

The form specification has already been pulled out to https://github.com/opendatakit/xforms-spec and is being maintained there. Should it continue to live separately or be incorporated into what these docs will become?

**Comment by adammichaelwood** [comment]
The underlying question here, which requires much discussion, is whether this docs repo should include *developer docs*.

I like writing developer docs, so I'm okay with it. But we should discuss options:

 - Dev docs live in this docs repo
 - A dev docs repo for the whole ODK project, this repo will be user/implementor docs
 - Individual dev docs repos for each project that might need them

I think I prefer options 1 and 2.

**Comment by lognaturel** [comment]
I'm pretty convinced that option 3 is going to be complicated logistically and may not even be feasible since the bounds between tools are not always clear.

How about having a dev doc folder in this repo initially and as dev docs grow considering breaking them out? That is, option 1 with the possibility of going to option 2 if deemed necessary?

As an aside, Dimagi has some nice prose [here](https://www.dimagi.com/javarosa/) on what OpenRosa was and its successes. That might be helpful for getting context.
