### ISSUE TITLE
Tips on regular expressions

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#91]
Regular expressions only apply to strings - https://github.com/opendatakit/javarosa/issues/137

Brief description of what they are; regex101.com is a useful resource

Might be useful to specifically mention phone number validation since that comes up a lot -- https://forum.opendatakit.org/t/want-to-make-restriction-on-entering-more-than-10-digits-mobile-number/9513

**Comment by tsah20** [comment]
@lognaturel Hi is this issue still open? Can I work on this

**Comment by adammichaelwood** [comment]
@tsah20 

This would be a doc within the Form Design unit.
Check out the XLSForm spec (specifically *constraints*) for details about how they would be used: http://xlsform.org/

It is open.

**Comment by troublemagnet** [comment]
if @tsah20 is not working on this, can I take this up?

**Comment by adammichaelwood** [comment]
I'm going with yes, as we have not heard from @tsah20 in two weeks.

Be sure to read the relevant links above, and also look at other forum support threads to see what sorts of things people are using the constraint regex for.

This doc would become part of *Form Design*

**Comment by troublemagnet** [comment]
@adammichaelwood Sure, I'm on it.

**Comment by ankita240796** [comment]
@opendatakit-bot claim
