### ISSUE TITLE
Tips for location

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#92]
Different phones have different GPSs.

Accuracy and battery can be controlled in Android settings - https://support.google.com/nexus/answer/3467281?hl=en

**Comment by mish24** [comment]
@opendatakit-bot claim

**Comment by adammichaelwood** [comment]
This would be a section of the best practices guide.

**Comment by troublemagnet** [comment]
@adammichaelwood if @mish24 is busy with other issues, may I work on this?
