### ISSUE TITLE
Document new "visible groups" in jump screen

### ISSUE THREAD

**Issue by cooperka** [opendatakit/docs#931]
XLSForm docs [here](http://xlsform.org/en/#grouping-questions), but probably shouldn't be modified. ODK docs sould probably be added on either [this page](https://docs.opendatakit.org/form-styling/) or [near this section](https://docs.opendatakit.org/form-logic/#repeating-questions-and-groups-of-questions).

Appearance is added in this PR: https://github.com/opendatakit/collect/pull/2764

> Adds the ability to designate groups as "visible" so they show up on the jump screen. You can then click on the group to see its children, similar to how you can view repeat instances.
> 
> To make a group visible, simply make sure it has a `ref` and a `label` like so:
> 
> ```xml
> <group ref="...">
>     <label>Some label</label>
>     ...
> </group>
> ```
> 
> In more technical terms, groups must be both **presentable** and **logical** (see [docs](https://opendatakit.github.io/xforms-spec/#groups) for definitions) in order to be visible.

**Comment by yanokwa** [comment]
The current docs don't really describe what happens in Jump or Edit, so maybe the best option might be: 
1. Adding a new section in https://docs.opendatakit.org/collect-filling-forms that describes editing a form with a few screenshots.
2. Having some text at https://docs.opendatakit.org/collect-filling-forms/#jumping-to-questions that says it's the same UI as editing.

**Comment by yanokwa** [comment]
The current docs don't really describe what happens in Jump or Edit, so maybe the best option might be: 
1. Adding a new section in https://docs.opendatakit.org/collect-filling-forms that describes editing a form with a few screenshots.
2. Having some text at https://docs.opendatakit.org/collect-filling-forms/#jumping-to-questions that says it's the same UI as editing.

**Comment by cooperka** [comment]
@yanokwa I just opened #950. I'm not completely sure what you wanted me to change in the `collect-filling-forms` section, but I did add docs to `form-logic`. Let me know if you think there should be further updates.

**Comment by yanokwa** [comment]
At https://docs.opendatakit.org/collect-filling-forms, I'm proposing adding a sub-section (maybe after #saving-a-partially-filled-form) called "Editing a saved form". It can be a few words that describes the functionality that already exists. But with new screenshots of your changes and you should note there that you can also add/remove repeats. 

Then at https://docs.opendatakit.org/collect-filling-forms/#jumping-to-questions, I'd explain that you can jump around, and drop the screenshot, and say it's the same UI as Editing a saved form (and link to that new text).

**Comment by yanokwa** [comment]
Closed by https://github.com/opendatakit/docs/pull/950
