### ISSUE TITLE
a tool for visualising and editing xlsform "templates"?

### ISSUE THREAD

**Issue by lorenzori** [opendatakit/docs#933]
my use case:
1) I create a large and complex xlsform, lets call it _template_.
2) a colleague opens _template_ in a webpage, removes some questions, edits some choices etc, then downloads the resulting xlsform.

Does a tool like this exist in the ecosystem? Closest I could find is Kobo's builder. 

thanks for the great work!

**Comment by yanokwa** [comment]
The short answer is no. 

If you have other support questions please post them to https://forum.opendatakit.org/c/support.
