### ISSUE TITLE
add documentation for new XPath functions: substring-before(), substring-after(), translate()

### ISSUE THREAD

**Issue by tiritea** [opendatakit/docs#936]
add relevant user documentation about new XPath functions. See:

https://github.com/opendatakit/javarosa/pull/395
https://github.com/opendatakit/javarosa/pull/393

**Comment by yanokwa** [comment]
@tiritea Will you have a chance to take this on in the next few days?

**Comment by tiritea** [comment]
I can start working on it this weekend. Changes shouldn’t take long, but I need to gets docs setup to test

**Comment by tiritea** [comment]
I can start working on it this weekend. Changes shouldn’t take long, but I need to gets docs setup to test

**Comment by tiritea** [comment]
Sorry. No idea how that got closed (I was responding via email...)

**Comment by tiritea** [comment]
FYI havent been able to get started on this yet, sorry. :-( When will these new functions be supported in Validate/XLSForm Online? I dont really want to publish them in docs till they're actually support, but then they really need to be in the docs ASAP soon thereafter.

**Comment by yanokwa** [comment]
Totally forgot about Validate. 😭

I have a PR at https://github.com/opendatakit/validate/pull/62 to get that updated. Once that's merged I'll do a release of Validate, then submit a PR to https://github.com/XLSForm/pyxform/issues/264. Once that's merged, we can do a release of XLSForm Online/Offline.

**Comment by tiritea** [comment]
Cheers. Is it ok if I try to time PR for doc change closer to Validate update? Some folks get annoyed when people post forms that may well work perfectly fine but dont pass Validate/XLSForm Online's illiberal scrutiny... I certainly dont want to facilitate that! 😁

**Comment by yanokwa** [comment]
Of course!

**Comment by yanokwa** [comment]
pyxform and Validate have been updated. You can test it at https://staging.xlsform.opendatakit.org. I'll put it on the production site with the release of Collect (eta Feb 25ish).

**Comment by tiritea** [comment]
K. I'll try to get a PR with associated doc update ready for soon thereafter.

**Comment by tiritea** [comment]
Ugh. Facing a bit of a crunch here so I might not be able to knock this out this before March 23. Will this be an issue for upcoming release?

**Comment by yanokwa** [comment]
The release is out, so it's not blocking anything. It's just something that has to be done so we can point people to it when they ask questions.

**Comment by tiritea** [comment]
done. sorry, it took a while to get docs setup (and even longer to figure out how to correctly spell "occurrence"...)
