### ISSUE TITLE
Style Guide testing

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#94]
- Find and implement appropriate testing tool (something like https://github.com/amperser/proselint)
- implement and document project-specific style guide (which we can edit with relative ease)
- incorporate into build script (#93)

**Comment by mish24** [comment]
https://pypi.python.org/pypi/restructuredtext_lint ---> this is a good tool!

**Comment by adammichaelwood** [comment]
Cool.

That looks like it lints for rst syntax, which might be redundant to Sphinx. 
(It may not be. I'm not sure.)

What we want for this task in particular is a tool that will let us specify style guide issues, 
for example, "Open Data Kit" versus "Open data kit" or "OpenDataKit" etc.

Proselint does that for a bunch of common grammar and spelling issues, but I don't know how easy it is to extend for project-specific styles.

There are some excellent node.js tools for doing this, which we can use if we have to. But I'd rather keep the toolchain to Python if we can, to keep things simple as possible for non-coding writers who may not be used to command line and installing npm and all that.

**Comment by Divya063** [comment]
@adammichaelwood For specific style guide issues [alex](https://github.com/wooorm/alex) is also quite good and easy to use, instructions to set up node js can be provided which just includes just a single command `sudo pip install nodeenv` and for testing purpose command line would be needed anyway.

**Comment by adammichaelwood** [comment]
> pip install nodeenv

GOOD FIND.

**Comment by Divya063** [comment]
@adammichaelwood I would like to work on this

**Comment by adammichaelwood** [comment]
I think this project is going to be substantial enough that it'll be worth doing as part of the Outreachy internship period. So I think let's not claim it or start working on it until then. If you'd like to include it in your project proposal, that would be great.

**Comment by Divya063** [comment]
@adammichaelwood Thanks for the suggestion :smile:

**Comment by adammichaelwood** [comment]
This issue didn't lay out the reqs as well as it should have.
So, let's have a conversation about what should actually happen.
----

## Writers should be able to run linter locally

I assume CLI is already included in Proselint, but if not we need to add it. And We want to to document it. We want to make it easy as possible to run the linter and get feedback locally. Docs should also link to PL docs, especially info on using various editors.

## Linter should be wired into the Sphinx build process locally

This probably just means adding it to `./b.sh`. 

## Linter should run on CircleCI builds

We should talk about whether we want to fail builds that violate rules.
(Is there a degree of rule? Like some are SERIOUS but others are SUGGESTIONS?)

## Writers should be able to add ignore rules 

There should be some way to tell the linter ignore certain rules on a per-paragraph basis.
(This ability should be accompanied by a Contrib process rule about explaining why such an exception is warranted.)

## We should be able to add linting rules **in our style guide texts**

This is the most off-the-beaten-path requirement.

We don't want a human-readable style guide in one place and then linter definitions somewhere else. We want a [literate programing](https://en.wikipedia.org/wiki/Literate_programming) approach where they are defined in the same document.

Something like...

```
Don't use apostrophes in decades
-------------------------------------

Don't use an apostrophe when talking about a decade.

.. rubric:: Right

1990s

.. rubric:: Wrong: 

1990's

.. code:: python
    :proselint:

    def check_decade_apostrophes_long(text):
        """Check the text for dates of the form XXX0's."""
        err = "dates_times.dates"
        msg = u"Apostrophes aren't needed for decades."
 
        regex = "\d\d\d0\'s"
        return existence_check(text, [regex], err, msg)
    
```

(Any of this is that is boilerplate, which could be abstracted away, should be.)

This makes it easier for us to keep our linting and our style guide in sync. It also gives contributors a  very clear picture of what we are checking for.

This also means that at build time (or in asynchronous some pre-build step, I guess) we have to extract the proselint-relevant python code and dump it into a `.py` file for execution.
