### ISSUE TITLE
Contributor guide additions for Windows

### ISSUE THREAD

**Issue by adammichaelwood** [opendatakit/docs#95]
The contributor's guide assumes a *nix platform. Additional information for Windows people would make the project much more contributor friendly, especially to non-coders and beginners.

I don't know enough about Windows (and especially running Python on Windows) to know what info is needed, but this would be a great project for someone who knows both platforms well enough to "translate".

**Comment by ronna** [comment]
@adammichaelwood 

I have succesfully setup the docs tool chain on Windows 10 following the *nix orriented instructions. I faced two issues:
1. I had installed Sphinx following instructions from their docs, my sphinx install gets uninstalled when I run the requirements file, thus there is no need to install sphinx first.
2. #118

**Comment by adammichaelwood** [comment]
> #118, 

see my comment there.

> my sphinx install gets uninstalled when I run the requirements file, thus there is no need to install sphinx first

Yes. That's why the contributor guide only mentions the requirements.txt file, and doesn't have `pip install sphinx`

**Comment by adammichaelwood** [comment]
Did you have to make any changes?
Did you use gitbash or powershell or linux subsystem or something else?
Have you been able to build and serve locally?

**Comment by adammichaelwood** [comment]
I should also say: congrats on getting the build going!
wooooo

**Comment by nadaa** [comment]
I used Cygwin and completed the build successfully. 
I added all installation steps in a txt file.  I still need to learn editing Sphnix. I also don't understand fully about git and branching.

**Comment by nadaa** [comment]
I thought to create a new .rst file to show instructions for windows (cygwin), and add a link from the contributing.rst  to the new file. What do you think @adammichaelwood ?

**Comment by adammichaelwood** [comment]
So the way to add this info to the docs is:

 - create a new `.rst` file -- make sure you follow the Sphinx/restructuredtext format and syntax in the contributor's guide
 - add a reference to the doc in the relevant table of contents directive in `index.rst`

You'll then need to commit your changes, push them to your Github copy, and then issue a pull request.

Try getting through that process on your own. If you can't figure it out, we'll set up a screenshare call or something and work through it.

**Comment by nadaa** [comment]
Hi,
I sent a pull request, can you please check it?

Thanks

**Comment by Divya063** [comment]
@adammichaelwood  I just used command prompt  (without using Cygwin) on windows and installed the build successfully

**Comment by nadaa** [comment]
@Divya060, What version of Windows you use?

**Comment by Divya063** [comment]
@nadaa Windows 10

**Comment by adammichaelwood** [comment]
closed via #145
