### ISSUE TITLE
Unexpected behaviour of the now() function

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/docs#961]
See discussion at https://forum.opendatakit.org/t/unexpected-behaviour-of-the-now-function/17302.

It would seem that now() that corresponds to the (last) opening of the form, not the last saved.

**Comment by lognaturel** [comment]
More at https://forum.opendatakit.org/t/unexpected-behaviour-of-the-now-function/17302/8?u=ln

Different implementations of ODK XForms may have different optimizations that result in a different result for the `datetime_last_saved` example. It should be removed.
