### ISSUE TITLE
Update "Location widgets" section

### ISSUE THREAD

**Issue by zestyping** [opendatakit/docs#968]
After the UI changes to the geo widgets are complete, the screenshots and some of the descriptions in [the "Location widgets" section](https://docs.opendatakit.org/form-question-types/#location-widgets) will need to be updated to match.

**Comment by lognaturel** [comment]
- [ ] Add geotrace description
- [ ] make it clear that trace can only save a line
- [ ] move warning about Aggregate field lengths above screenshots.
