### ISSUE TITLE
Describe how read-only, constraints and relevants interact

### ISSUE THREAD

**Issue by lognaturel** [opendatakit/docs#97]
https://forum.opendatakit.org/t/displaying-a-note-with-a-calculation-result-in-it/9547/9?u=ln

https://forum.opendatakit.org/t/odk-collect-calculate-fires-even-when-not-relevant/8923

**Comment by ankita240796** [comment]
@lognaturel Should I make a new doc for this ?

**Comment by adammichaelwood** [comment]
It would be a helpful addition to *Form Design*.

Be sure you are familiar with the xlsform.org specification, and actually try out the different permutations. It might even be good to create one large example xlsform with your examples.

**Comment by ankita240796** [comment]
Sure, I will do that. THanks!

**Comment by ankita240796** [comment]
@opendatakit-bot claim

**Comment by ankita240796** [comment]
@adammichaelwood There is no Form design doc still. PR #217 for the Form design doc is inactive. So where should this section be added? If @mish24 is not working on Form design doc, may I work on it?

**Comment by adammichaelwood** [comment]
>  If @mish24 is not working on Form design doc, may I work on it?

Part of the issue is that we're all still a little ambivalent (I think) about what a Form Design doc should include. 

> where should this section be added?
This could probably be a standalone document in the Form Building TOC.

**Comment by ankita240796** [comment]
@adammichaelwood Should I give a try to making a form design doc and then we can discuss what possible changes or additions are needed?

**Comment by adammichaelwood** [comment]
> Should I give a try to making a form design doc and then we can discuss what possible changes or additions are needed?

Not at the moment. I think this would be more sensible if I worked on it a bit and then cleaned up the existing issues related here.
