### ISSUE TITLE
Standard ODK presentations for community members

### ISSUE THREAD

**Issue by downeym** [opendatakit/docs#99]
It would be nice to adapt the previous ODK community presentation e.g. https://speakerdeck.com/nafundi/a-community-driven-future-for-open-data-kit into an one that could live in a Git repo, with easy collaborative editing, and using something like reveal.js to format it into a nice presentation.

Community members could present this in ODK meetups around the world, and could also fork & add local interest content, etc.

Finally, it might also serve as a "template" for people who want to create completely new ODK presentations, but use the same general design & template to save time.

**Comment by adammichaelwood** [comment]
i'm happy to have this live in docs. It could also potentially warrant its own repo.

**Comment by adammichaelwood** [comment]
Unless the scope of ODK docs changes, this issue does not belong here.
